final expectedJson = {
  "dstu2": [
    "File: './test/dstu2_examples/v2-tables.json'\ninput: CHESTÂ  :: output:CHESTÂ  is not a valid CodeFile: './test/dstu2_examples/v2-tables.json'\ninput: KIDNÂ  :: output:KIDNÂ  is not a valid CodeFile: './test/dstu2_examples/v2-tables.json'\ninput:   :: output:  is not a valid CodeFile: './test/dstu2_examples/v2-tables.json'\ninput: Â  :: output:Â  is not a valid Code",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change :: output:observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change is not a valid Id",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart :: output:observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart is not a valid Id",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant.json'\ninput: observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant :: output:observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant is not a valid Id",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant :: output:observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant is not a valid Id",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart.json'\ninput: observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart :: output:observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart is not a valid Id",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change.json'\ninput: observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change :: output:observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change is not a valid Id",
    "File: './test/dstu2_examples/v2-tables.json'\ninput: CHESTÂ  is not a valid Code :: output:CHESTÂ File: './test/dstu2_examples/v2-tables.json'\ninput: KIDNÂ  is not a valid Code :: output:KIDNÂ File: './test/dstu2_examples/v2-tables.json'\ninput:   is not a valid Code :: output: File: './test/dstu2_examples/v2-tables.json'\ninput: Â  is not a valid Code :: output:Â ",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant.json'\ninput: observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant.canonical.json'\ninput: observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-condition-gene-dnavariant",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart.json'\ninput: observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-chromosome-genomicstart",
    "File: './test/dstu2_examples/observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change.json'\ninput: observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change is not a valid Id :: output:observation-genetics-cg-prf-1a-Observation-gene-amino-acid-change"
  ],
  'stu3': [],
  'r4': [
    "File: './test/r4_examples/v2-tables.json'\ninput: CHESTÂ  :: output:CHESTÂ  is not a valid CodeFile: './test/r4_examples/v2-tables.json'\ninput: KIDNÂ  :: output:KIDNÂ  is not a valid CodeFile: './test/r4_examples/v2-tables.json'\ninput:   :: output:  is not a valid CodeFile: './test/r4_examples/v2-tables.json'\ninput: Â  :: output:Â  is not a valid Code",
    "File: './test/r4_examples/questionnaireresponse-extensions-QuestionnaireResponse-item-subject.json'\ninput: questionnaireresponse-extensions-QuestionnaireResponse-item-subject :: output:questionnaireresponse-extensions-QuestionnaireResponse-item-subject is not a valid Id",
    "File: './test/r4_examples/v2-tables.json'\ninput: CHESTÂ  is not a valid Code :: output:CHESTÂ File: './test/r4_examples/v2-tables.json'\ninput: KIDNÂ  is not a valid Code :: output:KIDNÂ File: './test/r4_examples/v2-tables.json'\ninput:   is not a valid Code :: output: File: './test/r4_examples/v2-tables.json'\ninput: Â  is not a valid Code :: output:Â ",
    "File: './test/r4_examples/questionnaireresponse-extensions-QuestionnaireResponse-item-subject.json'\ninput: questionnaireresponse-extensions-QuestionnaireResponse-item-subject is not a valid Id :: output:questionnaireresponse-extensions-QuestionnaireResponse-item-subject"
  ],
};
