part of 'resource.dart';

enum UsCoreResourceType {
  @JsonValue('AllergyIntolerance')
  AllergyIntolerance,
  @JsonValue('Bundle')
  Bundle,
  @JsonValue('CapabilityStatement')
  CapabilityStatement,
  @JsonValue('CarePlan')
  CarePlan,
  @JsonValue('CareTeam')
  CareTeam,
  @JsonValue('Condition')
  Condition,
  @JsonValue('Device')
  Device,
  @JsonValue('DiagnosticReport')
  DiagnosticReport,
  @JsonValue('DocumentReference')
  DocumentReference,
  @JsonValue('Encounter')
  Encounter,
  @JsonValue('Endpoint')
  Endpoint,
  @JsonValue('Goal')
  Goal,
  @JsonValue('Immunization')
  Immunization,
  @JsonValue('Location')
  Location,
  @JsonValue('Medication')
  Medication,
  @JsonValue('MedicationRequest')
  MedicationRequest,
  @JsonValue('Observation')
  Observation,
  @JsonValue('OperationOutcome')
  OperationOutcome,
  @JsonValue('Organization')
  Organization,
  @JsonValue('Patient')
  Patient,
  @JsonValue('Practitioner')
  Practitioner,
  @JsonValue('PractitionerRole')
  PractitionerRole,
  @JsonValue('Procedure')
  Procedure,
  @JsonValue('Provenance')
  Provenance,
}
