name: fhir_r4
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.9.5
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  # json_annotation: ^4.8.0
  serverpod_serialization: ^1.1.0
  uuid: ^3.0.7
  xml2json: ^5.3.6
  yaml: ^3.1.1

dev_dependencies:
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  test: ^1.23.1
