String GetDataType(String obj) {
  var newObj = obj.split('.')[0];
  var type;
  PrimitiveTypes().contains(newObj)
      ? type = 'primitiveTypes'
      : Resource().contains(newObj)
          ? type = 'resource'
          : Element().contains(newObj)
              ? type = 'element'
              : DomainResource().contains(newObj)
                  ? type = 'domainResource'
                  : type = 'resource';
  return type;
}

List<String> PrimitiveTypes() => [
      'id',
      'dateTime',
      'uri',
      'string',
      'code',
      'boolean',
      'decimal',
      'base64Binary',
      'unsignedInt',
      'positiveInt',
      'instant',
      'markdown',
      'integer',
      'xhtml',
      'date',
      'time',
      'oid',
    ];

List<String> Element() => [
      'Period',
      'Coding',
      'Range',
      'Quantity',
      'Attachment',
      'Ratio',
      'Annotation',
      'SampledData',
      'Reference',
      'CodeableConcept',
      'Identifier',
      'Signature',
      'ElementDefinition',
      'Timing',
      'Address',
      'HumanName',
      'Meta',
      'ContactPoint',
      'Extension',
      'BackboneElement',
      'Narrative',
      'Element',
    ];

List<String> DomainResource() => [
      'Condition',
      'ProcedureRequest',
      'DeviceComponent',
      'DeviceMetric',
      'Communication',
      'Organization',
      'ProcessRequest',
      'Group',
      'ValueSet',
      'Coverage',
      'ImmunizationRecommendation',
      'Appointment',
      'MedicationDispense',
      'DetectedIssue',
      'Slot',
      'PaymentNotice',
      'AppointmentResponse',
      'MedicationStatement',
      'ImplementationGuide',
      'EpisodeOfCare',
      'Questionnaire',
      'Composition',
      'OperationOutcome',
      'Conformance',
      'FamilyMemberHistory',
      'NamingSystem',
      'Media',
      'HealthcareService',
      'VisionPrescription',
      'DocumentReference',
      'Immunization',
      'Subscription',
      'OrderResponse',
      'ConceptMap',
      'ImagingStudy',
      'Practitioner',
      'CarePlan',
      'Provenance',
      'Device',
      'StructureDefinition',
      'Account',
      'Order',
      'Procedure',
      'Substance',
      'QuestionnaireResponse',
      'DeviceUseRequest',
      'DiagnosticReport',
      'Medication',
      'MessageHeader',
      'SupplyDelivery',
      'Schedule',
      'DocumentManifest',
      'DataElement',
      'EligibilityRequest',
      'MedicationAdministration',
      'Encounter',
      'PaymentReconciliation',
      'TestScript',
      'List',
      'DeviceUseStatement',
      'OperationDefinition',
      'ImagingObjectSelection',
      'Goal',
      'SearchParameter',
      'NutritionOrder',
      'ClaimResponse',
      'ReferralRequest',
      'ClinicalImpression',
      'BodySite',
      'Flag',
      'CommunicationRequest',
      'Claim',
      'RiskAssessment',
      'EnrollmentRequest',
      'Location',
      'ExplanationOfBenefit',
      'AllergyIntolerance',
      'Observation',
      'Contract',
      'RelatedPerson',
      'Basic',
      'ProcessResponse',
      'Specimen',
      'AuditEvent',
      'EnrollmentResponse',
      'SupplyRequest',
      'Patient',
      'EligibilityResponse',
      'MedicationOrder',
      'Person',
      'DiagnosticOrder',
    ];

List<String> Resource() => [
      'Parameters',
      'DomainResource',
      'Binary',
      'Bundle',
      'Resource',
    ];
