name: fhir_validation
description: A Dart/Flutter package for validating FHIR JSON.
version: 0.9.0
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir_validation

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  fhir: ^0.9.3
  fhir_auth: ^0.9.3
  fhir_path: ^0.9.4
  collection: ^1.16.0
  crypto: ^3.0.2
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.0
  riverpod_annotation: ^1.1.1
  shared_preferences: ^2.0.17
  universal_html: ^2.0.8
  url_launcher: ^6.1.8
  validators: ^3.0.0

dev_dependencies:
  ### ****** PUB.DEV ******
  # analyzer: ">=3.4.0 <=4.2.0"
  # analyzer: ^4.2.0
  build_runner: ^2.3.0
  freezed: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.6.0
  riverpod_generator: ^1.1.1
  test: ^1.22.2
