name: server
description: Interactively evaluate FHIRPath expressions
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  fhir:
    path: ../fhir
  fhir_db: 
    path: ../fhir_db
  shelf: ^1.4.1
  shelf_router: ^1.1.4