import '../uscore.dart';

class ResourceUtils {
  static const resourceTypeFromStringMap = {
    'AllergyIntolerance': UsCoreResourceType.AllergyIntolerance,
    'Bundle': UsCoreResourceType.Bundle,
    'CapabilityStatement': UsCoreResourceType.CapabilityStatement,
    'CarePlan': UsCoreResourceType.CarePlan,
    'CareTeam': UsCoreResourceType.CareTeam,
    'Condition': UsCoreResourceType.Condition,
    'Device': UsCoreResourceType.Device,
    'DiagnosticReport': UsCoreResourceType.DiagnosticReport,
    'DocumentReference': UsCoreResourceType.DocumentReference,
    'Encounter': UsCoreResourceType.Encounter,
    'Goal': UsCoreResourceType.Goal,
    'Immunization': UsCoreResourceType.Immunization,
    'Location': UsCoreResourceType.Location,
    'Medication': UsCoreResourceType.Medication,
    'MedicationRequest': UsCoreResourceType.MedicationRequest,
    'Observation': UsCoreResourceType.Observation,
    'Organization': UsCoreResourceType.Organization,
    'Patient': UsCoreResourceType.Patient,
    'Practitioner': UsCoreResourceType.Practitioner,
    'PractitionerRole': UsCoreResourceType.PractitionerRole,
    'Procedure': UsCoreResourceType.Procedure,
    'Provenance': UsCoreResourceType.Provenance,
    //

    //   'Account': UsCoreResourceType.Account,
    //   'ActivityDefinition': UsCoreResourceType.ActivityDefinition,
    //   'AdverseEvent': UsCoreResourceType.AdverseEvent,

    //   'Appointment': UsCoreResourceType.Appointment,
    //   'AppointmentResponse': UsCoreResourceType.AppointmentResponse,
    //   'AuditEvent': UsCoreResourceType.AuditEvent,
    //   'Basic': UsCoreResourceType.Basic,
    //   'Binary': UsCoreResourceType.Binary,
    //   'BiologicallyDerivedProduct': UsCoreResourceType.BiologicallyDerivedProduct,
    //   'BodyStructure': UsCoreResourceType.BodyStructure,

    //   'CatalogEntry': UsCoreResourceType.CatalogEntry,
    //   'ChargeItem': UsCoreResourceType.ChargeItem,
    //   'ChargeItemDefinition': UsCoreResourceType.ChargeItemDefinition,
    //   'Claim': UsCoreResourceType.Claim,
    //   'ClaimResponse': UsCoreResourceType.ClaimResponse,
    //   'ClinicalImpression': UsCoreResourceType.ClinicalImpression,
    //   'CodeSystem': UsCoreResourceType.CodeSystem,
    //   'Communication': UsCoreResourceType.Communication,
    //   'CommunicationRequest': UsCoreResourceType.CommunicationRequest,
    //   'CompartmentDefinition': UsCoreResourceType.CompartmentDefinition,
    //   'Composition': UsCoreResourceType.Composition,
    //   'ConceptMap': UsCoreResourceType.ConceptMap,

    //   'Consent': UsCoreResourceType.Consent,
    //   'Contract': UsCoreResourceType.Contract,
    //   'Coverage': UsCoreResourceType.Coverage,
    //   'CoverageEligibilityRequest': UsCoreResourceType.CoverageEligibilityRequest,
    //   'CoverageEligibilityResponse': UsCoreResourceType.CoverageEligibilityResponse,
    //   'DetectedIssue': UsCoreResourceType.DetectedIssue,

    //   'DeviceDefinition': UsCoreResourceType.DeviceDefinition,
    //   'DeviceMetric': UsCoreResourceType.DeviceMetric,
    //   'DeviceRequest': UsCoreResourceType.DeviceRequest,
    //   'DeviceUseStatement': UsCoreResourceType.DeviceUseStatement,

    //   'DocumentManifest': UsCoreResourceType.DocumentManifest,

    //   'EffectEvidenceSynthesis': UsCoreResourceType.EffectEvidenceSynthesis,

    //   'Endpoint': UsCoreResourceType.Endpoint,
    //   'EnrollmentRequest': UsCoreResourceType.EnrollmentRequest,
    //   'EnrollmentResponse': UsCoreResourceType.EnrollmentResponse,
    //   'EpisodeOfCare': UsCoreResourceType.EpisodeOfCare,
    //   'EventDefinition': UsCoreResourceType.EventDefinition,
    //   'Evidence': UsCoreResourceType.Evidence,
    //   'EvidenceVariable': UsCoreResourceType.EvidenceVariable,
    //   'ExampleScenario': UsCoreResourceType.ExampleScenario,
    //   'ExplanationOfBenefit': UsCoreResourceType.ExplanationOfBenefit,
    //   'FamilyMemberHistory': UsCoreResourceType.FamilyMemberHistory,
    //   'Flag': UsCoreResourceType.Flag,

    //   'GraphDefinition': UsCoreResourceType.GraphDefinition,
    //   'Group': UsCoreResourceType.Group,
    //   'GuidanceResponse': UsCoreResourceType.GuidanceResponse,
    //   'HealthcareService': UsCoreResourceType.HealthcareService,
    //   'ImagingStudy': UsCoreResourceType.ImagingStudy,

    //   'ImmunizationEvaluation': UsCoreResourceType.ImmunizationEvaluation,
    //   'ImmunizationRecommendation': UsCoreResourceType.ImmunizationRecommendation,
    //   'ImplementationGuide': UsCoreResourceType.ImplementationGuide,
    //   'InsurancePlan': UsCoreResourceType.InsurancePlan,
    //   'Invoice': UsCoreResourceType.Invoice,
    //   'Library': UsCoreResourceType.Library,
    //   'Linkage': UsCoreResourceType.Linkage,
    //   'List': UsCoreResourceType.List_,

    //   'Measure': UsCoreResourceType.Measure,
    //   'MeasureReport': UsCoreResourceType.MeasureReport,
    //   'Media': UsCoreResourceType.Media,

    //   'MedicationAdministration': UsCoreResourceType.MedicationAdministration,
    //   'MedicationDispense': UsCoreResourceType.MedicationDispense,
    //   'MedicationKnowledge': UsCoreResourceType.MedicationKnowledge,

    //   'MedicationStatement': UsCoreResourceType.MedicationStatement,
    //   'MedicinalProduct': UsCoreResourceType.MedicinalProduct,
    //   'MedicinalProductAuthorization':
    //       UsCoreResourceType.MedicinalProductAuthorization,
    //   'MedicinalProductContraindication':
    //       UsCoreResourceType.MedicinalProductContraindication,
    //   'MedicinalProductIndication': UsCoreResourceType.MedicinalProductIndication,
    //   'MedicinalProductIngredient': UsCoreResourceType.MedicinalProductIngredient,
    //   'MedicinalProductInteraction': UsCoreResourceType.MedicinalProductInteraction,
    //   'MedicinalProductManufactured': UsCoreResourceType.MedicinalProductManufactured,
    //   'MedicinalProductPackaged': UsCoreResourceType.MedicinalProductPackaged,
    //   'MedicinalProductPharmaceutical':
    //       UsCoreResourceType.MedicinalProductPharmaceutical,
    //   'MedicinalProductUndesirableEffect':
    //       UsCoreResourceType.MedicinalProductUndesirableEffect,
    //   'MessageDefinition': UsCoreResourceType.MessageDefinition,
    //   'MessageHeader': UsCoreResourceType.MessageHeader,
    //   'MolecularSequence': UsCoreResourceType.MolecularSequence,
    //   'NamingSystem': UsCoreResourceType.NamingSystem,
    //   'NutritionOrder': UsCoreResourceType.NutritionOrder,

    //   'ObservationDefinition': UsCoreResourceType.ObservationDefinition,
    //   'OperationDefinition': UsCoreResourceType.OperationDefinition,
    //   'OperationOutcome': UsCoreResourceType.OperationOutcome,

    //   'OrganizationAffiliation': UsCoreResourceType.OrganizationAffiliation,
    //   'Parameters': UsCoreResourceType.Parameters,

    //   'PaymentNotice': UsCoreResourceType.PaymentNotice,
    //   'PaymentReconciliation': UsCoreResourceType.PaymentReconciliation,
    //   'Person': UsCoreResourceType.Person,
    //   'PlanDefinition': UsCoreResourceType.PlanDefinition,

    //   'Questionnaire': UsCoreResourceType.Questionnaire,
    //   'QuestionnaireResponse': UsCoreResourceType.QuestionnaireResponse,
    //   'RelatedPerson': UsCoreResourceType.RelatedPerson,
    //   'RequestGroup': UsCoreResourceType.RequestGroup,
    //   'ResearchDefinition': UsCoreResourceType.ResearchDefinition,
    //   'ResearchElementDefinition': UsCoreResourceType.ResearchElementDefinition,
    //   'ResearchStudy': UsCoreResourceType.ResearchStudy,
    //   'ResearchSubject': UsCoreResourceType.ResearchSubject,
    //   'RiskAssessment': UsCoreResourceType.RiskAssessment,
    //   'RiskEvidenceSynthesis': UsCoreResourceType.RiskEvidenceSynthesis,
    //   'Schedule': UsCoreResourceType.Schedule,
    //   'SearchParameter': UsCoreResourceType.SearchParameter,
    //   'ServiceRequest': UsCoreResourceType.ServiceRequest,
    //   'Slot': UsCoreResourceType.Slot,
    //   'Specimen': UsCoreResourceType.Specimen,
    //   'SpecimenDefinition': UsCoreResourceType.SpecimenDefinition,
    //   'StructureDefinition': UsCoreResourceType.StructureDefinition,
    //   'StructureMap': UsCoreResourceType.StructureMap,
    //   'Subscription': UsCoreResourceType.Subscription,
    //   'Substance': UsCoreResourceType.Substance,
    //   'SubstanceNucleicAcid': UsCoreResourceType.SubstanceNucleicAcid,
    //   'SubstancePolymer': UsCoreResourceType.SubstancePolymer,
    //   'SubstanceProtein': UsCoreResourceType.SubstanceProtein,
    //   'SubstanceReferenceInformation':
    //       UsCoreResourceType.SubstanceReferenceInformation,
    //   'SubstanceSourceMaterial': UsCoreResourceType.SubstanceSourceMaterial,
    //   'SubstanceSpecification': UsCoreResourceType.SubstanceSpecification,
    //   'SupplyDelivery': UsCoreResourceType.SupplyDelivery,
    //   'SupplyRequest': UsCoreResourceType.SupplyRequest,
    //   'Task': UsCoreResourceType.Task,
    //   'TerminologyCapabilities': UsCoreResourceType.TerminologyCapabilities,
    //   'TestReport': UsCoreResourceType.TestReport,
    //   'TestScript': UsCoreResourceType.TestScript,
    //   'ValueSet': UsCoreResourceType.ValueSet,
    //   'VerificationResult': UsCoreResourceType.VerificationResult,
    //   'VisionPrescription': UsCoreResourceType.VisionPrescription,
  };

  static const resourceTypeToStringMap = {
    UsCoreResourceType.AllergyIntolerance: 'AllergyIntolerance',
    UsCoreResourceType.Bundle: 'Bundle',
    UsCoreResourceType.CapabilityStatement: 'CapabilityStatement',
    UsCoreResourceType.CarePlan: 'CarePlan',
    UsCoreResourceType.CareTeam: 'CareTeam',
    UsCoreResourceType.Condition: 'Condition',
    UsCoreResourceType.DiagnosticReport: 'DiagnosticReport',
    UsCoreResourceType.DocumentReference: 'DocumentReference',
    UsCoreResourceType.Encounter: 'Encounter',
    UsCoreResourceType.Goal: 'Goal',
    UsCoreResourceType.Immunization: 'Immunization',
    UsCoreResourceType.Location: 'Location',
    UsCoreResourceType.Medication: 'Medication',
    UsCoreResourceType.MedicationRequest: 'MedicationRequest',
    UsCoreResourceType.Observation: 'Observation',
    UsCoreResourceType.Organization: 'Organization',
    UsCoreResourceType.Patient: 'Patient',
    UsCoreResourceType.Practitioner: 'Practitioner',
    UsCoreResourceType.PractitionerRole: 'PractitionerRole',
    UsCoreResourceType.Procedure: 'Procedure',
    UsCoreResourceType.Provenance: 'Provenance',
    //

    // UsCoreResourceType.Account: 'Account',
    // UsCoreResourceType.ActivityDefinition: 'ActivityDefinition',
    // UsCoreResourceType.AdverseEvent: 'AdverseEvent',

    // UsCoreResourceType.Appointment: 'Appointment',
    // UsCoreResourceType.AppointmentResponse: 'AppointmentResponse',
    // UsCoreResourceType.AuditEvent: 'AuditEvent',
    // UsCoreResourceType.Basic: 'Basic',
    // UsCoreResourceType.Binary: 'Binary',
    // UsCoreResourceType.BiologicallyDerivedProduct: 'BiologicallyDerivedProduct',
    // UsCoreResourceType.BodyStructure: 'BodyStructure',

    // UsCoreResourceType.CatalogEntry: 'CatalogEntry',
    // UsCoreResourceType.ChargeItem: 'ChargeItem',
    // UsCoreResourceType.ChargeItemDefinition: 'ChargeItemDefinition',
    // UsCoreResourceType.Claim: 'Claim',
    // UsCoreResourceType.ClaimResponse: 'ClaimResponse',
    // UsCoreResourceType.ClinicalImpression: 'ClinicalImpression',
    // UsCoreResourceType.CodeSystem: 'CodeSystem',
    // UsCoreResourceType.Communication: 'Communication',
    // UsCoreResourceType.CommunicationRequest: 'CommunicationRequest',
    // UsCoreResourceType.CompartmentDefinition: 'CompartmentDefinition',
    // UsCoreResourceType.Composition: 'Composition',
    // UsCoreResourceType.ConceptMap: 'ConceptMap',

    // UsCoreResourceType.Consent: 'Consent',
    // UsCoreResourceType.Contract: 'Contract',
    // UsCoreResourceType.Coverage: 'Coverage',
    // UsCoreResourceType.CoverageEligibilityRequest: 'CoverageEligibilityRequest',
    // UsCoreResourceType.CoverageEligibilityResponse: 'CoverageEligibilityResponse',
    // UsCoreResourceType.DetectedIssue: 'DetectedIssue',
    // UsCoreResourceType.Device: 'Device',
    // UsCoreResourceType.DeviceDefinition: 'DeviceDefinition',
    // UsCoreResourceType.DeviceMetric: 'DeviceMetric',
    // UsCoreResourceType.DeviceRequest: 'DeviceRequest',
    // UsCoreResourceType.DeviceUseStatement: 'DeviceUseStatement',

    // UsCoreResourceType.DocumentManifest: 'DocumentManifest',

    // UsCoreResourceType.EffectEvidenceSynthesis: 'EffectEvidenceSynthesis',

    // UsCoreResourceType.Endpoint: 'Endpoint',
    // UsCoreResourceType.EnrollmentRequest: 'EnrollmentRequest',
    // UsCoreResourceType.EnrollmentResponse: 'EnrollmentResponse',
    // UsCoreResourceType.EpisodeOfCare: 'EpisodeOfCare',
    // UsCoreResourceType.EventDefinition: 'EventDefinition',
    // UsCoreResourceType.Evidence: 'Evidence',
    // UsCoreResourceType.EvidenceVariable: 'EvidenceVariable',
    // UsCoreResourceType.ExampleScenario: 'ExampleScenario',
    // UsCoreResourceType.ExplanationOfBenefit: 'ExplanationOfBenefit',
    // UsCoreResourceType.FamilyMemberHistory: 'FamilyMemberHistory',
    // UsCoreResourceType.Flag: 'Flag',

    // UsCoreResourceType.GraphDefinition: 'GraphDefinition',
    // UsCoreResourceType.Group: 'Group',
    // UsCoreResourceType.GuidanceResponse: 'GuidanceResponse',
    // UsCoreResourceType.HealthcareService: 'HealthcareService',
    // UsCoreResourceType.ImagingStudy: 'ImagingStudy',

    // UsCoreResourceType.ImmunizationEvaluation: 'ImmunizationEvaluation',
    // UsCoreResourceType.ImmunizationRecommendation: 'ImmunizationRecommendation',
    // UsCoreResourceType.ImplementationGuide: 'ImplementationGuide',
    // UsCoreResourceType.InsurancePlan: 'InsurancePlan',
    // UsCoreResourceType.Invoice: 'Invoice',
    // UsCoreResourceType.Library: 'Library',
    // UsCoreResourceType.Linkage: 'Linkage',
    // UsCoreResourceType.List_: 'List',

    // UsCoreResourceType.Measure: 'Measure',
    // UsCoreResourceType.MeasureReport: 'MeasureReport',
    // UsCoreResourceType.Media: 'Media',

    // UsCoreResourceType.MedicationAdministration: 'MedicationAdministration',
    // UsCoreResourceType.MedicationDispense: 'MedicationDispense',
    // UsCoreResourceType.MedicationKnowledge: 'MedicationKnowledge',

    // UsCoreResourceType.MedicationStatement: 'MedicationStatement',
    // UsCoreResourceType.MedicinalProduct: 'MedicinalProduct',
    // UsCoreResourceType.MedicinalProductAuthorization:
    //     'MedicinalProductAuthorization',
    // UsCoreResourceType.MedicinalProductContraindication:
    //     'MedicinalProductContraindication',
    // UsCoreResourceType.MedicinalProductIndication: 'MedicinalProductIndication',
    // UsCoreResourceType.MedicinalProductIngredient: 'MedicinalProductIngredient',
    // UsCoreResourceType.MedicinalProductInteraction: 'MedicinalProductInteraction',
    // UsCoreResourceType.MedicinalProductManufactured: 'MedicinalProductManufactured',
    // UsCoreResourceType.MedicinalProductPackaged: 'MedicinalProductPackaged',
    // UsCoreResourceType.MedicinalProductPharmaceutical:
    //     'MedicinalProductPharmaceutical',
    // UsCoreResourceType.MedicinalProductUndesirableEffect:
    //     'MedicinalProductUndesirableEffect',
    // UsCoreResourceType.MessageDefinition: 'MessageDefinition',
    // UsCoreResourceType.MessageHeader: 'MessageHeader',
    // UsCoreResourceType.MolecularSequence: 'MolecularSequence',
    // UsCoreResourceType.NamingSystem: 'NamingSystem',
    // UsCoreResourceType.NutritionOrder: 'NutritionOrder',

    // UsCoreResourceType.ObservationDefinition: 'ObservationDefinition',
    // UsCoreResourceType.OperationDefinition: 'OperationDefinition',
    // UsCoreResourceType.OperationOutcome: 'OperationOutcome',

    // UsCoreResourceType.OrganizationAffiliation: 'OrganizationAffiliation',
    // UsCoreResourceType.Parameters: 'Parameters',

    // UsCoreResourceType.PaymentNotice: 'PaymentNotice',
    // UsCoreResourceType.PaymentReconciliation: 'PaymentReconciliation',
    // UsCoreResourceType.Person: 'Person',
    // UsCoreResourceType.PlanDefinition: 'PlanDefinition',

    // UsCoreResourceType.Questionnaire: 'Questionnaire',
    // UsCoreResourceType.QuestionnaireResponse: 'QuestionnaireResponse',
    // UsCoreResourceType.RelatedPerson: 'RelatedPerson',
    // UsCoreResourceType.RequestGroup: 'RequestGroup',
    // UsCoreResourceType.ResearchDefinition: 'ResearchDefinition',
    // UsCoreResourceType.ResearchElementDefinition: 'ResearchElementDefinition',
    // UsCoreResourceType.ResearchStudy: 'ResearchStudy',
    // UsCoreResourceType.ResearchSubject: 'ResearchSubject',
    // UsCoreResourceType.RiskAssessment: 'RiskAssessment',
    // UsCoreResourceType.RiskEvidenceSynthesis: 'RiskEvidenceSynthesis',
    // UsCoreResourceType.Schedule: 'Schedule',
    // UsCoreResourceType.SearchParameter: 'SearchParameter',
    // UsCoreResourceType.ServiceRequest: 'ServiceRequest',
    // UsCoreResourceType.Slot: 'Slot',
    // UsCoreResourceType.Specimen: 'Specimen',
    // UsCoreResourceType.SpecimenDefinition: 'SpecimenDefinition',
    // UsCoreResourceType.StructureDefinition: 'StructureDefinition',
    // UsCoreResourceType.StructureMap: 'StructureMap',
    // UsCoreResourceType.Subscription: 'Subscription',
    // UsCoreResourceType.Substance: 'Substance',
    // UsCoreResourceType.SubstanceNucleicAcid: 'SubstanceNucleicAcid',
    // UsCoreResourceType.SubstancePolymer: 'SubstancePolymer',
    // UsCoreResourceType.SubstanceProtein: 'SubstanceProtein',
    // UsCoreResourceType.SubstanceReferenceInformation:
    //     'SubstanceReferenceInformation',
    // UsCoreResourceType.SubstanceSourceMaterial: 'SubstanceSourceMaterial',
    // UsCoreResourceType.SubstanceSpecification: 'SubstanceSpecification',
    // UsCoreResourceType.SupplyDelivery: 'SupplyDelivery',
    // UsCoreResourceType.SupplyRequest: 'SupplyRequest',
    // UsCoreResourceType.Task: 'Task',
    // UsCoreResourceType.TerminologyCapabilities: 'TerminologyCapabilities',
    // UsCoreResourceType.TestReport: 'TestReport',
    // UsCoreResourceType.TestScript: 'TestScript',
    // UsCoreResourceType.ValueSet: 'ValueSet',
    // UsCoreResourceType.VerificationResult: 'VerificationResult',
    // UsCoreResourceType.VisionPrescription: 'VisionPrescription',
  };
}
