name: fhir_hive
description: FHIR library of versions R4, STU3, DSTU2, and R5 (draft) for Dart & Flutter.
version: 0.9.5
homepage: https://www.fhirfli.dev/
repository: https://github.com/MayJuun/fhir/tree/main/fhir

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  fhir:
    path: ../fhir
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  objectbox: ^2.0.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.3
  # flutter pub run import_sorter:main
  import_sorter: ^4.6.0
  objectbox_generator: ^2.0.0
  test: ^1.23.1
