import 'package:fhir/r4.dart';

Endpoint endpointUsCore({
  Id? id,
  Meta? meta,
  Narrative? text,
  List<Resource>? contained,
  List<Identifier>? identifier,
  EndpointStatus? status,
  required Coding connectionType,
  String? name,
  Reference? managingOrganization,
  List<ContactPoint>? contact,
  Period? period,
  required List<CodeableConcept> payloadType,
  List<Code>? payloadMimeType,
  FhirUrl? address,
  List<String>? header,
}) =>
    Endpoint(
      id: id,
      meta: meta,
      text: text,
      contained: contained,
      identifier: identifier,
      status: status,
      connectionType: connectionType,
      name: name,
      managingOrganization: managingOrganization,
      contact: contact,
      period: period,
      payloadType: payloadType,
      payloadMimeType: payloadMimeType,
      address: address,
      header: header,
    );
