@freezed
abstract class Extension implements Extension, Resource {
factoryExtension({
id id,
extension extension,
url url,
_url _url,
valueBase64Binary valueBase64Binary,
_valueBase64Binary _valueBase64Binary,
valueBoolean valueBoolean,
_valueBoolean _valueBoolean,
valueCanonical valueCanonical,
_valueCanonical _valueCanonical,
valueCode valueCode,
_valueCode _valueCode,
valueDate valueDate,
_valueDate _valueDate,
valueDateTime valueDateTime,
_valueDateTime _valueDateTime,
valueDecimal valueDecimal,
_valueDecimal _valueDecimal,
valueId valueId,
_valueId _valueId,
valueInstant valueInstant,
_valueInstant _valueInstant,
valueInteger valueInteger,
_valueInteger _valueInteger,
valueMarkdown valueMarkdown,
_valueMarkdown _valueMarkdown,
valueOid valueOid,
_valueOid _valueOid,
valuePositiveInt valuePositiveInt,
_valuePositiveInt _valuePositiveInt,
valueString valueString,
_valueString _valueString,
valueTime valueTime,
_valueTime _valueTime,
valueUnsignedInt valueUnsignedInt,
_valueUnsignedInt _valueUnsignedInt,
valueUri valueUri,
_valueUri _valueUri,
valueUrl valueUrl,
_valueUrl _valueUrl,
valueUuid valueUuid,
_valueUuid _valueUuid,
valueAddress valueAddress,
valueAge valueAge,
valueAnnotation valueAnnotation,
valueAttachment valueAttachment,
valueCodeableConcept valueCodeableConcept,
valueCoding valueCoding,
valueContactPoint valueContactPoint,
valueCount valueCount,
valueDistance valueDistance,
valueDuration valueDuration,
valueHumanName valueHumanName,
valueIdentifier valueIdentifier,
valueMoney valueMoney,
valuePeriod valuePeriod,
valueQuantity valueQuantity,
valueRange valueRange,
valueRatio valueRatio,
valueReference valueReference,
valueSampledData valueSampledData,
valueSignature valueSignature,
valueTiming valueTiming,
valueContactDetail valueContactDetail,
valueContributor valueContributor,
valueDataRequirement valueDataRequirement,
valueExpression valueExpression,
valueParameterDefinition valueParameterDefinition,
valueRelatedArtifact valueRelatedArtifact,
valueTriggerDefinition valueTriggerDefinition,
valueUsageContext valueUsageContext,
valueDosage valueDosage,
valueMeta valueMeta,
}) = _Extension

 factory Extension.fromJson(Map<String,dynamic> json) => _$ExtensionFromJson(json);
}

@freezed
abstract class Narrative implements Narrative, Resource {
factoryNarrative({
id id,
extension extension,
status status,
_status _status,
div div,
}) = _Narrative

 factory Narrative.fromJson(Map<String,dynamic> json) => _$NarrativeFromJson(json);
}

@freezed
abstract class Reference implements Reference, Resource {
factoryReference({
id id,
extension extension,
reference reference,
_reference _reference,
type type,
_type _type,
identifier identifier,
display display,
_display _display,
}) = _Reference

 factory Reference.fromJson(Map<String,dynamic> json) => _$ReferenceFromJson(json);
}

@freezed
abstract class Meta implements Meta, Resource {
factoryMeta({
id id,
extension extension,
versionId versionId,
_versionId _versionId,
lastUpdated lastUpdated,
_lastUpdated _lastUpdated,
source source,
_source _source,
profile profile,
security security,
tag tag,
}) = _Meta

 factory Meta.fromJson(Map<String,dynamic> json) => _$MetaFromJson(json);
}

@freezed
abstract class Dosage implements Dosage, Resource {
factoryDosage({
id id,
extension extension,
modifierExtension modifierExtension,
sequence sequence,
_sequence _sequence,
text text,
_text _text,
additionalInstruction additionalInstruction,
patientInstruction patientInstruction,
_patientInstruction _patientInstruction,
timing timing,
asNeededBoolean asNeededBoolean,
_asNeededBoolean _asNeededBoolean,
asNeededCodeableConcept asNeededCodeableConcept,
site site,
route route,
method method,
doseAndRate doseAndRate,
maxDosePerPeriod maxDosePerPeriod,
maxDosePerAdministration maxDosePerAdministration,
maxDosePerLifetime maxDosePerLifetime,
}) = _Dosage

 factory Dosage.fromJson(Map<String,dynamic> json) => _$DosageFromJson(json);
}

@freezed
abstract class DosageDoseAndRate implements DosageDoseAndRate, Resource {
factoryDosageDoseAndRate({
id id,
extension extension,
modifierExtension modifierExtension,
type type,
doseRange doseRange,
doseQuantity doseQuantity,
rateRatio rateRatio,
rateRange rateRange,
rateQuantity rateQuantity,
}) = _DosageDoseAndRate

 factory DosageDoseAndRate.fromJson(Map<String,dynamic> json) => _$DosageDoseAndRateFromJson(json);
}

@freezed
abstract class ElementDefinition implements ElementDefinition, Resource {
factoryElementDefinition({
id id,
extension extension,
modifierExtension modifierExtension,
path path,
_path _path,
representation representation,
_representation _representation,
sliceName sliceName,
_sliceName _sliceName,
sliceIsConstraining sliceIsConstraining,
_sliceIsConstraining _sliceIsConstraining,
label label,
_label _label,
code code,
slicing slicing,
short short,
_short _short,
definition definition,
_definition _definition,
comment comment,
_comment _comment,
requirements requirements,
_requirements _requirements,
alias alias,
_alias _alias,
min min,
_min _min,
max max,
_max _max,
base base,
contentReference contentReference,
_contentReference _contentReference,
type type,
defaultValueBase64Binary defaultValueBase64Binary,
_defaultValueBase64Binary _defaultValueBase64Binary,
defaultValueBoolean defaultValueBoolean,
_defaultValueBoolean _defaultValueBoolean,
defaultValueCanonical defaultValueCanonical,
_defaultValueCanonical _defaultValueCanonical,
defaultValueCode defaultValueCode,
_defaultValueCode _defaultValueCode,
defaultValueDate defaultValueDate,
_defaultValueDate _defaultValueDate,
defaultValueDateTime defaultValueDateTime,
_defaultValueDateTime _defaultValueDateTime,
defaultValueDecimal defaultValueDecimal,
_defaultValueDecimal _defaultValueDecimal,
defaultValueId defaultValueId,
_defaultValueId _defaultValueId,
defaultValueInstant defaultValueInstant,
_defaultValueInstant _defaultValueInstant,
defaultValueInteger defaultValueInteger,
_defaultValueInteger _defaultValueInteger,
defaultValueMarkdown defaultValueMarkdown,
_defaultValueMarkdown _defaultValueMarkdown,
defaultValueOid defaultValueOid,
_defaultValueOid _defaultValueOid,
defaultValuePositiveInt defaultValuePositiveInt,
_defaultValuePositiveInt _defaultValuePositiveInt,
defaultValueString defaultValueString,
_defaultValueString _defaultValueString,
defaultValueTime defaultValueTime,
_defaultValueTime _defaultValueTime,
defaultValueUnsignedInt defaultValueUnsignedInt,
_defaultValueUnsignedInt _defaultValueUnsignedInt,
defaultValueUri defaultValueUri,
_defaultValueUri _defaultValueUri,
defaultValueUrl defaultValueUrl,
_defaultValueUrl _defaultValueUrl,
defaultValueUuid defaultValueUuid,
_defaultValueUuid _defaultValueUuid,
defaultValueAddress defaultValueAddress,
defaultValueAge defaultValueAge,
defaultValueAnnotation defaultValueAnnotation,
defaultValueAttachment defaultValueAttachment,
defaultValueCodeableConcept defaultValueCodeableConcept,
defaultValueCoding defaultValueCoding,
defaultValueContactPoint defaultValueContactPoint,
defaultValueCount defaultValueCount,
defaultValueDistance defaultValueDistance,
defaultValueDuration defaultValueDuration,
defaultValueHumanName defaultValueHumanName,
defaultValueIdentifier defaultValueIdentifier,
defaultValueMoney defaultValueMoney,
defaultValuePeriod defaultValuePeriod,
defaultValueQuantity defaultValueQuantity,
defaultValueRange defaultValueRange,
defaultValueRatio defaultValueRatio,
defaultValueReference defaultValueReference,
defaultValueSampledData defaultValueSampledData,
defaultValueSignature defaultValueSignature,
defaultValueTiming defaultValueTiming,
defaultValueContactDetail defaultValueContactDetail,
defaultValueContributor defaultValueContributor,
defaultValueDataRequirement defaultValueDataRequirement,
defaultValueExpression defaultValueExpression,
defaultValueParameterDefinition defaultValueParameterDefinition,
defaultValueRelatedArtifact defaultValueRelatedArtifact,
defaultValueTriggerDefinition defaultValueTriggerDefinition,
defaultValueUsageContext defaultValueUsageContext,
defaultValueDosage defaultValueDosage,
defaultValueMeta defaultValueMeta,
meaningWhenMissing meaningWhenMissing,
_meaningWhenMissing _meaningWhenMissing,
orderMeaning orderMeaning,
_orderMeaning _orderMeaning,
fixedBase64Binary fixedBase64Binary,
_fixedBase64Binary _fixedBase64Binary,
fixedBoolean fixedBoolean,
_fixedBoolean _fixedBoolean,
fixedCanonical fixedCanonical,
_fixedCanonical _fixedCanonical,
fixedCode fixedCode,
_fixedCode _fixedCode,
fixedDate fixedDate,
_fixedDate _fixedDate,
fixedDateTime fixedDateTime,
_fixedDateTime _fixedDateTime,
fixedDecimal fixedDecimal,
_fixedDecimal _fixedDecimal,
fixedId fixedId,
_fixedId _fixedId,
fixedInstant fixedInstant,
_fixedInstant _fixedInstant,
fixedInteger fixedInteger,
_fixedInteger _fixedInteger,
fixedMarkdown fixedMarkdown,
_fixedMarkdown _fixedMarkdown,
fixedOid fixedOid,
_fixedOid _fixedOid,
fixedPositiveInt fixedPositiveInt,
_fixedPositiveInt _fixedPositiveInt,
fixedString fixedString,
_fixedString _fixedString,
fixedTime fixedTime,
_fixedTime _fixedTime,
fixedUnsignedInt fixedUnsignedInt,
_fixedUnsignedInt _fixedUnsignedInt,
fixedUri fixedUri,
_fixedUri _fixedUri,
fixedUrl fixedUrl,
_fixedUrl _fixedUrl,
fixedUuid fixedUuid,
_fixedUuid _fixedUuid,
fixedAddress fixedAddress,
fixedAge fixedAge,
fixedAnnotation fixedAnnotation,
fixedAttachment fixedAttachment,
fixedCodeableConcept fixedCodeableConcept,
fixedCoding fixedCoding,
fixedContactPoint fixedContactPoint,
fixedCount fixedCount,
fixedDistance fixedDistance,
fixedDuration fixedDuration,
fixedHumanName fixedHumanName,
fixedIdentifier fixedIdentifier,
fixedMoney fixedMoney,
fixedPeriod fixedPeriod,
fixedQuantity fixedQuantity,
fixedRange fixedRange,
fixedRatio fixedRatio,
fixedReference fixedReference,
fixedSampledData fixedSampledData,
fixedSignature fixedSignature,
fixedTiming fixedTiming,
fixedContactDetail fixedContactDetail,
fixedContributor fixedContributor,
fixedDataRequirement fixedDataRequirement,
fixedExpression fixedExpression,
fixedParameterDefinition fixedParameterDefinition,
fixedRelatedArtifact fixedRelatedArtifact,
fixedTriggerDefinition fixedTriggerDefinition,
fixedUsageContext fixedUsageContext,
fixedDosage fixedDosage,
fixedMeta fixedMeta,
patternBase64Binary patternBase64Binary,
_patternBase64Binary _patternBase64Binary,
patternBoolean patternBoolean,
_patternBoolean _patternBoolean,
patternCanonical patternCanonical,
_patternCanonical _patternCanonical,
patternCode patternCode,
_patternCode _patternCode,
patternDate patternDate,
_patternDate _patternDate,
patternDateTime patternDateTime,
_patternDateTime _patternDateTime,
patternDecimal patternDecimal,
_patternDecimal _patternDecimal,
patternId patternId,
_patternId _patternId,
patternInstant patternInstant,
_patternInstant _patternInstant,
patternInteger patternInteger,
_patternInteger _patternInteger,
patternMarkdown patternMarkdown,
_patternMarkdown _patternMarkdown,
patternOid patternOid,
_patternOid _patternOid,
patternPositiveInt patternPositiveInt,
_patternPositiveInt _patternPositiveInt,
patternString patternString,
_patternString _patternString,
patternTime patternTime,
_patternTime _patternTime,
patternUnsignedInt patternUnsignedInt,
_patternUnsignedInt _patternUnsignedInt,
patternUri patternUri,
_patternUri _patternUri,
patternUrl patternUrl,
_patternUrl _patternUrl,
patternUuid patternUuid,
_patternUuid _patternUuid,
patternAddress patternAddress,
patternAge patternAge,
patternAnnotation patternAnnotation,
patternAttachment patternAttachment,
patternCodeableConcept patternCodeableConcept,
patternCoding patternCoding,
patternContactPoint patternContactPoint,
patternCount patternCount,
patternDistance patternDistance,
patternDuration patternDuration,
patternHumanName patternHumanName,
patternIdentifier patternIdentifier,
patternMoney patternMoney,
patternPeriod patternPeriod,
patternQuantity patternQuantity,
patternRange patternRange,
patternRatio patternRatio,
patternReference patternReference,
patternSampledData patternSampledData,
patternSignature patternSignature,
patternTiming patternTiming,
patternContactDetail patternContactDetail,
patternContributor patternContributor,
patternDataRequirement patternDataRequirement,
patternExpression patternExpression,
patternParameterDefinition patternParameterDefinition,
patternRelatedArtifact patternRelatedArtifact,
patternTriggerDefinition patternTriggerDefinition,
patternUsageContext patternUsageContext,
patternDosage patternDosage,
patternMeta patternMeta,
example example,
minValueDate minValueDate,
_minValueDate _minValueDate,
minValueDateTime minValueDateTime,
_minValueDateTime _minValueDateTime,
minValueInstant minValueInstant,
_minValueInstant _minValueInstant,
minValueTime minValueTime,
_minValueTime _minValueTime,
minValueDecimal minValueDecimal,
_minValueDecimal _minValueDecimal,
minValueInteger minValueInteger,
_minValueInteger _minValueInteger,
minValuePositiveInt minValuePositiveInt,
_minValuePositiveInt _minValuePositiveInt,
minValueUnsignedInt minValueUnsignedInt,
_minValueUnsignedInt _minValueUnsignedInt,
minValueQuantity minValueQuantity,
maxValueDate maxValueDate,
_maxValueDate _maxValueDate,
maxValueDateTime maxValueDateTime,
_maxValueDateTime _maxValueDateTime,
maxValueInstant maxValueInstant,
_maxValueInstant _maxValueInstant,
maxValueTime maxValueTime,
_maxValueTime _maxValueTime,
maxValueDecimal maxValueDecimal,
_maxValueDecimal _maxValueDecimal,
maxValueInteger maxValueInteger,
_maxValueInteger _maxValueInteger,
maxValuePositiveInt maxValuePositiveInt,
_maxValuePositiveInt _maxValuePositiveInt,
maxValueUnsignedInt maxValueUnsignedInt,
_maxValueUnsignedInt _maxValueUnsignedInt,
maxValueQuantity maxValueQuantity,
maxLength maxLength,
_maxLength _maxLength,
condition condition,
_condition _condition,
constraint constraint,
mustSupport mustSupport,
_mustSupport _mustSupport,
isModifier isModifier,
_isModifier _isModifier,
isModifierReason isModifierReason,
_isModifierReason _isModifierReason,
isSummary isSummary,
_isSummary _isSummary,
binding binding,
mapping mapping,
}) = _ElementDefinition

 factory ElementDefinition.fromJson(Map<String,dynamic> json) => _$ElementDefinitionFromJson(json);
}

@freezed
abstract class ElementDefinitionSlicing implements ElementDefinitionSlicing, Resource {
factoryElementDefinitionSlicing({
id id,
extension extension,
modifierExtension modifierExtension,
discriminator discriminator,
description description,
_description _description,
ordered ordered,
_ordered _ordered,
rules rules,
_rules _rules,
}) = _ElementDefinitionSlicing

 factory ElementDefinitionSlicing.fromJson(Map<String,dynamic> json) => _$ElementDefinitionSlicingFromJson(json);
}

@freezed
abstract class ElementDefinitionDiscriminator implements ElementDefinitionDiscriminator, Resource {
factoryElementDefinitionDiscriminator({
id id,
extension extension,
modifierExtension modifierExtension,
type type,
_type _type,
path path,
_path _path,
}) = _ElementDefinitionDiscriminator

 factory ElementDefinitionDiscriminator.fromJson(Map<String,dynamic> json) => _$ElementDefinitionDiscriminatorFromJson(json);
}

@freezed
abstract class ElementDefinitionBase implements ElementDefinitionBase, Resource {
factoryElementDefinitionBase({
id id,
extension extension,
modifierExtension modifierExtension,
path path,
_path _path,
min min,
_min _min,
max max,
_max _max,
}) = _ElementDefinitionBase

 factory ElementDefinitionBase.fromJson(Map<String,dynamic> json) => _$ElementDefinitionBaseFromJson(json);
}

@freezed
abstract class ElementDefinitionType implements ElementDefinitionType, Resource {
factoryElementDefinitionType({
id id,
extension extension,
modifierExtension modifierExtension,
code code,
_code _code,
profile profile,
targetProfile targetProfile,
aggregation aggregation,
_aggregation _aggregation,
versioning versioning,
_versioning _versioning,
}) = _ElementDefinitionType

 factory ElementDefinitionType.fromJson(Map<String,dynamic> json) => _$ElementDefinitionTypeFromJson(json);
}

@freezed
abstract class ElementDefinitionExample implements ElementDefinitionExample, Resource {
factoryElementDefinitionExample({
id id,
extension extension,
modifierExtension modifierExtension,
label label,
_label _label,
valueBase64Binary valueBase64Binary,
_valueBase64Binary _valueBase64Binary,
valueBoolean valueBoolean,
_valueBoolean _valueBoolean,
valueCanonical valueCanonical,
_valueCanonical _valueCanonical,
valueCode valueCode,
_valueCode _valueCode,
valueDate valueDate,
_valueDate _valueDate,
valueDateTime valueDateTime,
_valueDateTime _valueDateTime,
valueDecimal valueDecimal,
_valueDecimal _valueDecimal,
valueId valueId,
_valueId _valueId,
valueInstant valueInstant,
_valueInstant _valueInstant,
valueInteger valueInteger,
_valueInteger _valueInteger,
valueMarkdown valueMarkdown,
_valueMarkdown _valueMarkdown,
valueOid valueOid,
_valueOid _valueOid,
valuePositiveInt valuePositiveInt,
_valuePositiveInt _valuePositiveInt,
valueString valueString,
_valueString _valueString,
valueTime valueTime,
_valueTime _valueTime,
valueUnsignedInt valueUnsignedInt,
_valueUnsignedInt _valueUnsignedInt,
valueUri valueUri,
_valueUri _valueUri,
valueUrl valueUrl,
_valueUrl _valueUrl,
valueUuid valueUuid,
_valueUuid _valueUuid,
valueAddress valueAddress,
valueAge valueAge,
valueAnnotation valueAnnotation,
valueAttachment valueAttachment,
valueCodeableConcept valueCodeableConcept,
valueCoding valueCoding,
valueContactPoint valueContactPoint,
valueCount valueCount,
valueDistance valueDistance,
valueDuration valueDuration,
valueHumanName valueHumanName,
valueIdentifier valueIdentifier,
valueMoney valueMoney,
valuePeriod valuePeriod,
valueQuantity valueQuantity,
valueRange valueRange,
valueRatio valueRatio,
valueReference valueReference,
valueSampledData valueSampledData,
valueSignature valueSignature,
valueTiming valueTiming,
valueContactDetail valueContactDetail,
valueContributor valueContributor,
valueDataRequirement valueDataRequirement,
valueExpression valueExpression,
valueParameterDefinition valueParameterDefinition,
valueRelatedArtifact valueRelatedArtifact,
valueTriggerDefinition valueTriggerDefinition,
valueUsageContext valueUsageContext,
valueDosage valueDosage,
valueMeta valueMeta,
}) = _ElementDefinitionExample

 factory ElementDefinitionExample.fromJson(Map<String,dynamic> json) => _$ElementDefinitionExampleFromJson(json);
}

@freezed
abstract class ElementDefinitionConstraint implements ElementDefinitionConstraint, Resource {
factoryElementDefinitionConstraint({
id id,
extension extension,
modifierExtension modifierExtension,
key key,
_key _key,
requirements requirements,
_requirements _requirements,
severity severity,
_severity _severity,
human human,
_human _human,
expression expression,
_expression _expression,
xpath xpath,
_xpath _xpath,
source source,
}) = _ElementDefinitionConstraint

 factory ElementDefinitionConstraint.fromJson(Map<String,dynamic> json) => _$ElementDefinitionConstraintFromJson(json);
}

@freezed
abstract class ElementDefinitionBinding implements ElementDefinitionBinding, Resource {
factoryElementDefinitionBinding({
id id,
extension extension,
modifierExtension modifierExtension,
strength strength,
_strength _strength,
description description,
_description _description,
valueSet valueSet,
}) = _ElementDefinitionBinding

 factory ElementDefinitionBinding.fromJson(Map<String,dynamic> json) => _$ElementDefinitionBindingFromJson(json);
}

@freezed
abstract class ElementDefinitionMapping implements ElementDefinitionMapping, Resource {
factoryElementDefinitionMapping({
id id,
extension extension,
modifierExtension modifierExtension,
identity identity,
_identity _identity,
language language,
_language _language,
map map,
_map _map,
comment comment,
_comment _comment,
}) = _ElementDefinitionMapping

 factory ElementDefinitionMapping.fromJson(Map<String,dynamic> json) => _$ElementDefinitionMappingFromJson(json);
}

