import 'package:freezed_annotation/freezed_annotation.dart';

enum ResourceConditionalRead {
  @JsonValue('not-supported')
  not_supported,
  @JsonValue('modified-since')
  modified_since,
  @JsonValue('not-match')
  not_match,
  @JsonValue('full-support')
  full_support,
  @JsonValue('unknown')
  unknown,
}

enum ResourceConditionalDelete {
  @JsonValue('not-supported')
  not_supported,
  @JsonValue('single')
  single,
  @JsonValue('multiple')
  multiple,
  @JsonValue('unknown')
  unknown,
}

enum ResourceReferencePolicy {
  @JsonValue('literal')
  literal,
  @JsonValue('logical')
  logical,
  @JsonValue('resolves')
  resolves,
  @JsonValue('enforced')
  enforced,
  @JsonValue('local')
  local,
  @JsonValue('unknown')
  unknown,
}

enum SearchParamType {
  @JsonValue('number')
  number,
  @JsonValue('date')
  date,
  @JsonValue('string')
  string,
  @JsonValue('token')
  token,
  @JsonValue('reference')
  reference,
  @JsonValue('composite')
  composite,
  @JsonValue('quantity')
  quantity,
  @JsonValue('uri')
  uri,
  @JsonValue('special')
  special,
  @JsonValue('unknown')
  unknown,
}

enum MessageDefinitionStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum MessageDefinitionCategory {
  @JsonValue('consequence')
  consequence,
  @JsonValue('currency')
  currency,
  @JsonValue('notification')
  notification,
  @JsonValue('unknown')
  unknown,
}

enum MessageDefinitionResponseRequired {
  @JsonValue('always')
  always,
  @JsonValue('on-error')
  on_error,
  @JsonValue('never')
  never,
  @JsonValue('on-success')
  on_success,
  @JsonValue('unknown')
  unknown,
}

enum CapabilityStatementStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum CapabilityStatementKind {
  @JsonValue('instance')
  instance,
  @JsonValue('capability')
  capability,
  @JsonValue('requirements')
  requirements,
  @JsonValue('unknown')
  unknown,
}

enum CapabilityStatementFhirVersion {
  @JsonValue('0.01')
  v0_01,
  @JsonValue('0.05')
  v0_05,
  @JsonValue('0.06')
  v0_06,
  @JsonValue('0.11')
  v0_11,
  @JsonValue('0.0.80')
  v0_0_80,
  @JsonValue('0.0.81')
  v0_0_81,
  @JsonValue('0.0.82')
  v0_0_82,
  @JsonValue('0.4.0')
  v0_4_0,
  @JsonValue('0.5.0')
  v0_5_0,
  @JsonValue('1.0.0')
  v1_0_0,
  @JsonValue('1.0.1')
  v1_0_1,
  @JsonValue('1.0.2')
  v1_0_2,
  @JsonValue('1.1.0')
  v1_1_0,
  @JsonValue('1.4.0')
  v1_4_0,
  @JsonValue('1.6.0')
  v1_6_0,
  @JsonValue('1.8.0')
  v1_8_0,
  @JsonValue('3.0.0')
  v3_0_0,
  @JsonValue('3.0.1')
  v3_0_1,
  @JsonValue('3.3.0')
  v3_3_0,
  @JsonValue('3.5.0')
  v3_5_0,
  @JsonValue('4.0.0')
  v4_0_0,
  @JsonValue('4.0.1')
  v4_0_1,
  @JsonValue('unknown')
  unknown,
}

enum RestMode {
  @JsonValue('client')
  client,
  @JsonValue('server')
  server,
  @JsonValue('unknown')
  unknown,
}

enum ResourceVersioning {
  @JsonValue('no-version')
  no_version,
  @JsonValue('versioned')
  versioned,
  @JsonValue('versioned-update')
  versioned_update,
  @JsonValue('unknown')
  unknown,
}

enum RestInteractionCode {
  @JsonValue('transaction')
  transaction,
  @JsonValue('batch')
  batch,
  @JsonValue('search-system')
  not_match,
  @JsonValue('history-system')
  full_support,
  @JsonValue('unknown')
  unknown,
}

enum CapabilityStatementSearchParamType {
  @JsonValue('not-supported')
  not_supported,
  @JsonValue('single')
  single,
  @JsonValue('multiple')
  multiple,
  @JsonValue('unknown')
  unknown,
}

enum ResourceInteractionCode {
  @JsonValue('read')
  read,
  @JsonValue('vread')
  vread,
  @JsonValue('update')
  update,
  @JsonValue('patch')
  patch,
  @JsonValue('delete')
  delete,
  @JsonValue('history-instance')
  history_instance,
  @JsonValue('history-type')
  history_type,
  @JsonValue('create')
  create,
  @JsonValue('search-type')
  search_type,
  @JsonValue('unknown')
  unknown,
}

enum SupportedMessageMode {
  @JsonValue('sender')
  sender,
  @JsonValue('receiver')
  receiver,
  @JsonValue('unknown')
  unknown,
}

enum DocumentMode {
  @JsonValue('producer')
  producer,
  @JsonValue('consumer')
  conumer,
  @JsonValue('unknown')
  unknown,
}

enum CompartmentDefinitionStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum CompartmentDefinitionCode {
  @JsonValue('Patient')
  Patient,
  @JsonValue('Encounter')
  Encounter,
  @JsonValue('RelatedPerson')
  RelatedPerson,
  @JsonValue('Practitioner')
  Practitioner,
  @JsonValue('Device')
  Device,
  @JsonValue('unknown')
  unknown,
}

enum OperationDefinitionStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum OperationDefinitionKind {
  @JsonValue('operation')
  operation,
  @JsonValue('query')
  query,
  @JsonValue('unknown')
  unknown,
}

enum OperationDefinitionParameterUse {
  @JsonValue('in')
  in_,
  @JsonValue('out')
  out,
  @JsonValue('unknown')
  unknown,
}

enum OperationDefinitionParameterSearchType {
  @JsonValue('number')
  number,
  @JsonValue('date')
  date,
  @JsonValue('string')
  string,
  @JsonValue('token')
  token,
  @JsonValue('reference')
  reference,
  @JsonValue('composite')
  composite,
  @JsonValue('quantity')
  quantity,
  @JsonValue('uri')
  uri,
  @JsonValue('special')
  special,
  @JsonValue('unknown')
  unknown,
}

enum OperationDefinitionBindingStrength {
  @JsonValue('required')
  required,
  @JsonValue('extensible')
  extensible,
  @JsonValue('preferred')
  preferred,
  @JsonValue('example')
  example,
  @JsonValue('unknown')
  unknown,
}

enum ExampleScenarioStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum ExampleScenarioActorType {
  @JsonValue('person')
  person,
  @JsonValue('entity')
  entity,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapStructureMode {
  @JsonValue('source')
  source,
  @JsonValue('queried')
  queried,
  @JsonValue('target')
  target,
  @JsonValue('produced')
  produced,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapGroupTypeMode {
  @JsonValue('none')
  none,
  @JsonValue('types')
  types,
  @JsonValue('type-and-types')
  type_and_types,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapInputMode {
  @JsonValue('source')
  source,
  @JsonValue('target')
  target,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapSourceListMode {
  @JsonValue('first')
  first,
  @JsonValue('not_first')
  not_first,
  @JsonValue('last')
  last,
  @JsonValue('not_last')
  not_last,
  @JsonValue('only_one')
  only_one,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapTargetContextType {
  @JsonValue('type')
  type,
  @JsonValue('variable')
  variable,
  @JsonValue('unknown')
  unknown,
}

enum StructureMapTargetTransform {
  @JsonValue('create')
  create,
  @JsonValue('copy')
  copy,
  @JsonValue('truncate')
  truncate,
  @JsonValue('escape')
  escape,
  @JsonValue('cast')
  cast,
  @JsonValue('append')
  append,
  @JsonValue('translate')
  translate,
  @JsonValue('reference')
  reference,
  @JsonValue('dateOp')
  dateOp,
  @JsonValue('uuid')
  uuid,
  @JsonValue('pointer')
  pointer,
  @JsonValue('evaluate')
  evaluate,
  @JsonValue('cc')
  cc,
  @JsonValue('c')
  c,
  @JsonValue('qty')
  qty,
  @JsonValue('id')
  id,
  @JsonValue('cp')
  cp,
  @JsonValue('unknown')
  unknown,
}

enum ImplementationGuideStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum ImplementationGuideLicense {
  @JsonValue('not-open-source')
  not_open_source,
  @JsonValue('0bsd')
  obsd,
  @JsonValue('aal')
  aal,
  @JsonValue('abstyles')
  abstyles,
  @JsonValue('adobe-2006')
  adobe_2006,
  @JsonValue('adobe-glyph')
  adobe_glyph,
  @JsonValue('adsl')
  adsl,
  @JsonValue('afl-1.1')
  afl_v1_1,
  @JsonValue('afl-1.2')
  afl_v1_2,
  @JsonValue('afl-2.0')
  afl_2_0,
  @JsonValue('afl-2.1')
  afl_2_1,
  @JsonValue('afl-3.0')
  afl_3_0,
  @JsonValue('afmparse')
  afmparse,
  @JsonValue('agpl-1.0-only')
  agpl_v1_0_only,
  @JsonValue('agpl-1.0-or-later')
  agpl_v1_0_or_later,
  @JsonValue('agpl-3.0-only')
  agpl_v3_0_only,
  @JsonValue('agpl-3.0-or-later')
  agpl_v3_0_or_later,
  @JsonValue('aladdin')
  aladdin,
  @JsonValue('amdplpa')
  amdplpa,
  @JsonValue('aml')
  aml,
  @JsonValue('ampas')
  ampas,
  @JsonValue('antlr-pd')
  antlr_pd,
  @JsonValue('apache-1.0')
  apache_v1_0,
  @JsonValue('apache-1.1')
  apache_v1_1,
  @JsonValue('apache-2.0')
  apache_v2_0,
  @JsonValue('apafml')
  apafml,
  @JsonValue('apl-1.0')
  apl_v1_0,
  @JsonValue('apsl-1.0')
  apsl_v1_0,
  @JsonValue('apsl-1.1')
  apsl_v1_1,
  @JsonValue('apsl-1.2')
  apsl_v1_2,
  @JsonValue('apsl-2.0')
  apsl_v2_0,
  @JsonValue('artistic-1.0-cl8')
  artistic_1v_0_cl8,
  @JsonValue('artistic-1.0-perl')
  artistic_v1_0_perl,
  @JsonValue('artistic-1.0')
  artistic_v1_0,
  @JsonValue('artistic-2.0')
  artistic_v2_0,
  @JsonValue('bahyph')
  bahyph,
  @JsonValue('barr')
  barr,
  @JsonValue('beerware')
  beerware,
  @JsonValue('bittorrent-1.0')
  bittorrent_v1_0,
  @JsonValue('bittorrent-1.1')
  bittorrent_v1_1,
  @JsonValue('borceux')
  borceux,
  @JsonValue('bsd-1-clause')
  bsd_1_clause,
  @JsonValue('bsd-2-clause-freebsd')
  bsd_2_clause_freebsd,
  @JsonValue('bsd-2-clause-netbsd')
  bsd_2_clause_netbsd,
  @JsonValue('bsd-2-clause-patent')
  bsd_2_clause_patent,
  @JsonValue('bsd-2-clause')
  bsd_2_clause,
  @JsonValue('bsd-3-clause-attribution')
  bsd_3_clause_attribution,
  @JsonValue('bsd-3-clause-clear')
  bsd_3_clause_clear,
  @JsonValue('bsd-3-clause-lbnl')
  bsd_3_clause_lbnl,
  @JsonValue('bsd-3-clause-no-nuclear-license-2014')
  bsd_3_clause_no_nuclear_license_2014,
  @JsonValue('bsd-3-clause-no-nuclear-license')
  bsd_3_clause_no_nuclear_license,
  @JsonValue('bsd-3-clause-no-nuclear-warranty')
  bsd_3_clause_no_nuclear_warranty,
  @JsonValue('bsd-3-clause')
  bsd_3_clause,
  @JsonValue('bsd-4-clause-uc')
  bsd_4_clause_uc,
  @JsonValue('bsd-4-clause')
  bsd_4_clause,
  @JsonValue('bsd-protection')
  bsd_protection,
  @JsonValue('bsd-source-code')
  bsd_source_code,
  @JsonValue('bsl-1.0')
  bsd_v1_0,
  @JsonValue('bzip2-1.0.5')
  bzip2_v1_0_5,
  @JsonValue('bzip2-1.0.6')
  bzip2_v1_0_6,
  @JsonValue('caldera')
  caldera,
  @JsonValue('catosl-1.1')
  catosl_v1_1,
  @JsonValue('cc-by-1.0')
  cc_by_v1_0,
  @JsonValue('cc-by-2.0')
  cc_by_v2_0,
  @JsonValue('cc-by-2.5')
  cc_by_v2_5,
  @JsonValue('cc-by-3.0')
  cc_by_v3_0,
  @JsonValue('cc-by-4.0')
  cc_by_v4_0,
  @JsonValue('cc-by-nc-1.0')
  cc_by_nc_v1_0,
  @JsonValue('cc-by-nc-2.0')
  cc_by_nc_v2_0,
  @JsonValue('cc-by-nc-2.5')
  cc_by_nc_v2_5,
  @JsonValue('cc-by-nc-3.0')
  cc_by_nc_v3_0,
  @JsonValue('cc-by-nc-4.0')
  cc_by_nc_v4_0,
  @JsonValue('cc-by-nc-nd-1.0')
  cc_by_nc_nd_v1_0,
  @JsonValue('cc-by-nc-nd-2.0')
  cc_by_nc_nd_v2_0,
  @JsonValue('cc-by-nc-nd-2.5')
  cc_by_nc_nd_v2_5,
  @JsonValue('cc-by-nc-nd-3.0')
  cc_by_nc_nd_v3_0,
  @JsonValue('cc-by-nc-nd-4.0')
  cc_by_nc_nd_v4_0,
  @JsonValue('cc-by-nc-sa-1.0')
  cc_by_nc_sa_v1_0,
  @JsonValue('cc-by-nc-sa-2.0')
  cc_by_nc_sa_v2_0,
  @JsonValue('cc-by-nc-sa-2.5')
  cc_by_nc_sa_v2_5,
  @JsonValue('cc-by-nc-sa-3.0')
  cc_by_nc_sa_v3_0,
  @JsonValue('cc-by-nc-sa-4.0')
  cc_by_nc_sa_v4_0,
  @JsonValue('cc-by-nd-1.0')
  cc_by_nd_v1_0,
  @JsonValue('cc-by-nd-2.0')
  cc_by_nd_v2_0,
  @JsonValue('cc-by-nd-2.5')
  cc_by_nd_v2_5,
  @JsonValue('cc-by-nd-3.0')
  cc_by_nd_v3_0,
  @JsonValue('cc-by-nd-4.0')
  cc_by_nd_v4_0,
  @JsonValue('cc-by-sa-1.0')
  cc_by_sa_v1_0,
  @JsonValue('cc-by-sa-2.0')
  cc_by_sa_v2_0,
  @JsonValue('cc-by-sa-2.5')
  cc_by_sa_v2_5,
  @JsonValue('cc-by-sa-3.0')
  cc_by_sa_v3_0,
  @JsonValue('cc-by-sa-4.0')
  cc_by_sa_v4_0,
  @JsonValue('cc0-1.0')
  cc0_v1_0,
  @JsonValue('cddl-1.0')
  cddl_v1_0,
  @JsonValue('cddl-1.1')
  cddl_v1_1,
  @JsonValue('cdla-permissive-1.0')
  cdla_permissive_v1_0,
  @JsonValue('cdla-sharing-1.0')
  cdla_sharing_v1_0,
  @JsonValue('cecill-1.0')
  cecill_v1_0,
  @JsonValue('cecill-1.1')
  cecill_v1_1,
  @JsonValue('cecill-2.0')
  cecill_v2_0,
  @JsonValue('cecill-2.1')
  cecill_v2_1,
  @JsonValue('cecill-b')
  cecill_b,
  @JsonValue('cecill-c')
  cecill_c,
  @JsonValue('clartistic')
  clartistic,
  @JsonValue('cnri-jython')
  cnri_jython,
  @JsonValue('cnri-python-gpl-compatible')
  cnri_python_gpl_compatible,
  @JsonValue('cnri-python')
  cnri_python,
  @JsonValue('condor-1.1')
  condor_v1_1,
  @JsonValue('cpal-1.0')
  cpal_v1_0,
  @JsonValue('cpl-1.0')
  cpl_v1_0,
  @JsonValue('cpol-1.02')
  cpol_v1_02,
  @JsonValue('crossword')
  crossword,
  @JsonValue('crystalstacker')
  crystalstacker,
  @JsonValue('cua-opl-1.0')
  cua_opl_v1_0,
  @JsonValue('cube')
  cube,
  @JsonValue('curl')
  curl,
  @JsonValue('d-fsl-1.0')
  d_fsl_v1_0,
  @JsonValue('diffmark')
  diffmark,
  @JsonValue('doc')
  doc,
  @JsonValue('dotseqn')
  dotseqn,
  @JsonValue('dsdp')
  dsdp,
  @JsonValue('dvipdfm')
  dvipdfm,
  @JsonValue('ecl-1.0')
  ecl_v1_0,
  @JsonValue('ecl-2.0')
  ecl_v2_0,
  @JsonValue('efl-1.0')
  efl_v1_0,
  @JsonValue('efl-2.0')
  efl_v2_0,
  @JsonValue('egenix')
  egenix,
  @JsonValue('entessa')
  entessa,
  @JsonValue('epl-1.0')
  epl_v1_0,
  @JsonValue('epl-2.0')
  epl_v2_0,
  @JsonValue('erlpl-1.1')
  erlpl_v1_1,
  @JsonValue('eudatagrid')
  eudatagrid,
  @JsonValue('eupl-1.0')
  eupl_v1_0,
  @JsonValue('eupl-1.1')
  eupl_v1_1,
  @JsonValue('eupl-1.2')
  eupl_v1_2,
  @JsonValue('eurosym')
  eurosym,
  @JsonValue('fair')
  fair,
  @JsonValue('frameworx-1.0')
  frameworx_v1_0,
  @JsonValue('freeimage')
  freeimage,
  @JsonValue('fsfap')
  fsfap,
  @JsonValue('fsful')
  fsful,
  @JsonValue('fsfullr')
  fsfullr,
  @JsonValue('ftl')
  ftl,
  @JsonValue('gfdl-1.1-only')
  gfdl_v1_1_only,
  @JsonValue('gfdl-1.1-or-later')
  gfdl_v1_1_or_later,
  @JsonValue('gfdl-1.2-only')
  gfdl_v1_2_only,
  @JsonValue('gfdl-1.2-or-later')
  gfdl_v1_2_or_later,
  @JsonValue('gfdl-1.3-only')
  gfdl_v1_3_only,
  @JsonValue('gfdl-1.3-or-later')
  gfdl_v1_3_or_later,
  @JsonValue('giftware')
  giftware,
  @JsonValue('gl2ps')
  gl2ps,
  @JsonValue('glide')
  glide,
  @JsonValue('glulxe')
  glulxe,
  @JsonValue('gnuplot')
  gnuplot,
  @JsonValue('gpl-1.0-only')
  gpl_v1_0_only,
  @JsonValue('gpl-1.0-or-later')
  gpl_v1_0_or_later,
  @JsonValue('gpl-2.0-only')
  gpl_v2_0_only,
  @JsonValue('gpl-2.0-or-later')
  gpl_v2_0_or_later,
  @JsonValue('gpl-3.0-only')
  gpl_v3_0_only,
  @JsonValue('gpl-3.0-or-later')
  gpl_v3_0_or_later,
  @JsonValue('gsoap-1.3b')
  gsoap_v1_3b,
  @JsonValue('haskellreport')
  haskellreport,
  @JsonValue('hpnd')
  hpnd,
  @JsonValue('ibm-pibs')
  ibm_pibs,
  @JsonValue('icu')
  icu,
  @JsonValue('ijg')
  ijg,
  @JsonValue('imagemagick')
  imagemagick,
  @JsonValue('imatix')
  imatix,
  @JsonValue('imlib2')
  imlib2,
  @JsonValue('info-zip')
  info_zip,
  @JsonValue('intel-acpi')
  intel_acpi,
  @JsonValue('intel')
  intel,
  @JsonValue('interbase-1.0')
  interbase_v1_0,
  @JsonValue('ipa')
  ipa,
  @JsonValue('ipl-1.0')
  ipl_v1_0,
  @JsonValue('isc')
  isc,
  @JsonValue('jasper-2.0')
  jasper_v2_0,
  @JsonValue('json')
  json,
  @JsonValue('lal-1.2')
  lal_v1_2,
  @JsonValue('lal-1.3')
  lal_v1_3,
  @JsonValue('latex2e')
  latex2e,
  @JsonValue('leptonica')
  leptonica,
  @JsonValue('lgpl-2.0-only')
  lgpl_v2_0_only,
  @JsonValue('lgpl-2.0-or-later')
  lgpl_v2_0_or_later,
  @JsonValue('lgpl-2.1-only')
  lgpl_v2_1_only,
  @JsonValue('lgpl-2.1-or-later')
  lgpl_v2_1_or_later,
  @JsonValue('lgpl-3.0-only')
  lgpl_v3_0_only,
  @JsonValue('lgpl-3.0-or-later')
  lgpl_v3_0_or_later,
  @JsonValue('lgpllr')
  lgpllr,
  @JsonValue('libpng')
  libpng,
  @JsonValue('libtiff')
  libtiff,
  @JsonValue('liliq-p-1.1')
  liliq_p_v1_1,
  @JsonValue('liliq-r-1.1')
  liliq_r_v1_1,
  @JsonValue('liliq-rplus-1.1')
  liliq_rplus_v1_1,
  @JsonValue('linux-openib')
  linux_openib,
  @JsonValue('lpl-1.0')
  lpl_v1_0,
  @JsonValue('lpl-1.02')
  lpl_v1_02,
  @JsonValue('lppl-1.0')
  lppl_v1_0,
  @JsonValue('lppl-1.1')
  lppl_v1_1,
  @JsonValue('lppl-1.2')
  lppl_v1_2,
  @JsonValue('lppl-1.3a')
  lppl_v1_3a,
  @JsonValue('lppl-1.3c')
  lppl_v1_3c,
  @JsonValue('makeindex')
  makeindex,
  @JsonValue('miros')
  miros,
  @JsonValue('mit-0')
  mit_0,
  @JsonValue('mit-advertising')
  mit_advertising,
  @JsonValue('mit-cmu')
  mit_cmu,
  @JsonValue('mit-enna')
  mit_enna,
  @JsonValue('mit-feh')
  mit_feh,
  @JsonValue('mit')
  mit,
  @JsonValue('mitnfa')
  mitnfa,
  @JsonValue('motosoto')
  motosoto,
  @JsonValue('mpich2')
  mpich2,
  @JsonValue('mpl-1.0')
  mpl_v1_0,
  @JsonValue('mpl-1.1')
  mpl_v1_1,
  @JsonValue('mpl-2.0-no-copyleft-exception')
  mpl_v2_0_no_copyleft_exception,
  @JsonValue('mpl-2.0')
  mpl_v2_0,
  @JsonValue('ms-pl')
  ms_pl,
  @JsonValue('ms-rl')
  ms_rl,
  @JsonValue('mtll')
  mtll,
  @JsonValue('multics')
  multics,
  @JsonValue('mup')
  mup,
  @JsonValue('nasa-1.3')
  nasa_v1_3,
  @JsonValue('naumen')
  naumen,
  @JsonValue('nbpl-1.0')
  nbpl_v1_0,
  @JsonValue('ncsa')
  ncsa,
  @JsonValue('net-snmp')
  net_snmp,
  @JsonValue('netcdf')
  netcdf,
  @JsonValue('newsletr')
  newsletr,
  @JsonValue('ngpl')
  ngpl,
  @JsonValue('nlod-1.0')
  nlod_v1_0,
  @JsonValue('nlpl')
  nlpl,
  @JsonValue('nokia')
  nokia,
  @JsonValue('nosl')
  nosl,
  @JsonValue('noweb')
  noweb,
  @JsonValue('npl-1.0')
  npl_v1_0,
  @JsonValue('npl-1.1')
  npl_v1_1,
  @JsonValue('nposl-3.0')
  nposl_v3_0,
  @JsonValue('nrl')
  nrl,
  @JsonValue('ntp')
  ntp,
  @JsonValue('occt-pl')
  occt_pl,
  @JsonValue('oclc-2.0')
  oclc_v2_0,
  @JsonValue('odbl-1.0')
  odbl_v1_0,
  @JsonValue('ofl-1.0')
  ofl_v1_0,
  @JsonValue('ofl-1.1')
  ofl_v1_1,
  @JsonValue('ogtsl')
  ogtsl,
  @JsonValue('oldap-1.1')
  oldap_v1_1,
  @JsonValue('oldap-1.2')
  oldap_v1_2,
  @JsonValue('oldap-1.3')
  oldap_v1_3,
  @JsonValue('oldap-1.4')
  oldap_v1_4,
  @JsonValue('oldap-2.0.1')
  oldap_v2_v0_1,
  @JsonValue('oldap-2.0')
  oldap_v2_0,
  @JsonValue('oldap-2.1')
  oldap_v2_1,
  @JsonValue('oldap-2.2.1')
  oldap_v2_2_1,
  @JsonValue('oldap-2.2.2')
  oldap_v2_2_2,
  @JsonValue('oldap-2.2')
  oldap_v2_2,
  @JsonValue('oldap-2.3')
  oldap_v2_3,
  @JsonValue('oldap-2.4')
  oldap_v2_4,
  @JsonValue('oldap-2.5')
  oldap_v2_5,
  @JsonValue('oldap-2.6')
  oldap_v2_6,
  @JsonValue('oldap-2.7')
  oldap_v2_7,
  @JsonValue('oldap-2.8')
  oldap_v2_8,
  @JsonValue('oml')
  oml,
  @JsonValue('openssl')
  openssl,
  @JsonValue('opl-1.0')
  opl_v1_0,
  @JsonValue('oset-pl-2.1')
  oset_pl_v2_1,
  @JsonValue('osl-1.0')
  osl_v1_0,
  @JsonValue('osl-1.1')
  osl_v1_1,
  @JsonValue('osl-2.0')
  osl_v2_0,
  @JsonValue('osl-2.1')
  osl_v2_1,
  @JsonValue('osl-3.0')
  osl_v3_0,
  @JsonValue('pddl-1.0')
  pddl_v1_0,
  @JsonValue('php-3.0')
  php_v3_0,
  @JsonValue('php-3.01')
  php_v3_01,
  @JsonValue('plexus')
  plexus,
  @JsonValue('postgresql')
  postgresql,
  @JsonValue('psfrag')
  psfrag,
  @JsonValue('psutils')
  psutils,
  @JsonValue('python-2.0')
  python_v2_0,
  @JsonValue('qhull')
  qhull,
  @JsonValue('qpl-1.0')
  qpl_v1_0,
  @JsonValue('rdisc')
  rdisc,
  @JsonValue('rhecos-1.1')
  rhecos_v1_1,
  @JsonValue('rpl-1.1')
  rpl_v1_1,
  @JsonValue('rpl-1.5')
  rpl_v1_5,
  @JsonValue('rpsl-1.0')
  rpsl_v1_0,
  @JsonValue('rsa-md')
  rsa_md,
  @JsonValue('rscpl')
  rscpl,
  @JsonValue('ruby')
  ruby,
  @JsonValue('sax-pd')
  sax_pd,
  @JsonValue('saxpath')
  saxpath,
  @JsonValue('scea')
  scea,
  @JsonValue('sendmail')
  sendmail,
  @JsonValue('sgi-b-1.0')
  sgi_b_v1_0,
  @JsonValue('sgi-b-1.1')
  sgi_b_v1_1,
  @JsonValue('sgi-b-2.0')
  sgi_b_v2_0,
  @JsonValue('simpl-2.0')
  simpl_v2_0,
  @JsonValue('sissl-1.2')
  sissl_v1_2,
  @JsonValue('sissl')
  sissl,
  @JsonValue('sleepycat')
  sleepycat,
  @JsonValue('smlnj')
  smlnj,
  @JsonValue('smppl')
  smppl,
  @JsonValue('snia')
  snia,
  @JsonValue('spencer-86')
  spencer_86,
  @JsonValue('spencer-94')
  spencer_94,
  @JsonValue('spencer-99')
  spencer_99,
  @JsonValue('spl-1.0')
  spl_v1_0,
  @JsonValue('sugarcrm-1.1.3')
  sugarcrm_v1_1_3,
  @JsonValue('swl')
  swl,
  @JsonValue('tcl')
  tcl,
  @JsonValue('tcp-wrappers')
  tcp_wrappers,
  @JsonValue('tmate')
  tmate,
  @JsonValue('torque-1.1')
  torque_v1_1,
  @JsonValue('tosl')
  tosl,
  @JsonValue('unicode-dfs-2015')
  unicode_dfs_2015,
  @JsonValue('unicode-dfs-2016')
  unicode_dfs_2016,
  @JsonValue('unicode-tou')
  unicode_tou,
  @JsonValue('unlicense')
  unlicense,
  @JsonValue('upl-1.0')
  upl_v1_0,
  @JsonValue('vim')
  vim,
  @JsonValue('vostrom')
  vostrom,
  @JsonValue('vsl-1.0')
  vsl_v1_0,
  @JsonValue('w3c-19980720')
  w3c_19980720,
  @JsonValue('w3c-20150513')
  w3c_20150513,
  @JsonValue('w3c')
  w3c,
  @JsonValue('watcom-1.0')
  watcom_v1_0,
  @JsonValue('wsuipa')
  wsuipa,
  @JsonValue('wtfpl')
  wtfpl,
  @JsonValue('x11')
  x11,
  @JsonValue('xerox')
  xerox,
  @JsonValue('xfree86-1.1')
  xfree86_v1_1,
  @JsonValue('xinetd')
  xinetd,
  @JsonValue('xnet')
  xnet,
  @JsonValue('xpp')
  xpp,
  @JsonValue('xskat')
  xskat,
  @JsonValue('ypl-1.0')
  ypl_v1_0,
  @JsonValue('ypl-1.1')
  ypl_v1_1,
  @JsonValue('zed')
  zed,
  @JsonValue('zend-2.0')
  zend_v2_0,
  @JsonValue('zimbra-1.3')
  zimbra_v1_3,
  @JsonValue('zimbra-1.4')
  zimbra_v1_4,
  @JsonValue('zlib-acknowledgement')
  zlib_acknowledgement,
  @JsonValue('zlib')
  zlib,
  @JsonValue('zpl-1.1')
  zpl_v1_1,
  @JsonValue('zpl-2.0')
  zpl_v2_0,
  @JsonValue('zpl-2.1')
  zpl_v2_1,
  @JsonValue('unknown')
  unknown,
}

enum ImplementationGuidePageGeneration {
  @JsonValue('html')
  html,
  @JsonValue('markdown')
  markdown,
  @JsonValue('xml')
  xml,
  @JsonValue('generated')
  generated,
  @JsonValue('unknown')
  unknown,
}

enum ImplementationGuideParameterCode {
  @JsonValue('apply')
  apply,
  @JsonValue('path-resource')
  path_resource,
  @JsonValue('path-pages')
  path_pages,
  @JsonValue('path-tx-cache')
  path_tx_cache,
  @JsonValue('expansion-parameter')
  expansion_parameter,
  @JsonValue('rule-broken-links')
  rule_broken_links,
  @JsonValue('generate-xml')
  generate_xml,
  @JsonValue('generate-json')
  generate_json,
  @JsonValue('generate-turtle')
  generate_turtle,
  @JsonValue('html-template')
  html_template,
  @JsonValue('unknown')
  unknown,
}

enum SearchParameterStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum SearchParameterType {
  @JsonValue('number')
  number,
  @JsonValue('date')
  date,
  @JsonValue('string')
  string,
  @JsonValue('token')
  token,
  @JsonValue('reference')
  reference,
  @JsonValue('composite')
  composite,
  @JsonValue('quantity')
  quantity,
  @JsonValue('uri')
  uri,
  @JsonValue('special')
  special,
  @JsonValue('unknown')
  unknown,
}

enum SearchParameterXpathUsage {
  @JsonValue('normal')
  normal,
  @JsonValue('phonetic')
  phonetic,
  @JsonValue('nearby')
  nearby,
  @JsonValue('distance')
  distance,
  @JsonValue('other')
  other,
  @JsonValue('unknown')
  unknown,
}

enum GraphDefinitionStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum GraphDefinitionCompartmentUse {
  @JsonValue('condition')
  condition,
  @JsonValue('requirement')
  requirement,
  @JsonValue('unknown')
  unknown,
}

enum GraphDefinitionCompartmentRule {
  @JsonValue('identical')
  identical,
  @JsonValue('matching')
  matching,
  @JsonValue('different')
  different,
  @JsonValue('custom')
  custom,
  @JsonValue('unknown')
  unknown,
}

enum StructureDefinitionStatus {
  @JsonValue('draft')
  draft,
  @JsonValue('active')
  active,
  @JsonValue('retired')
  retired,
  @JsonValue('unknown')
  unknown,
}

enum StructureDefinitionFhirVersion {
  @JsonValue('0.01')
  v0_01,
  @JsonValue('0.05')
  v0_05,
  @JsonValue('0.06')
  v0_06,
  @JsonValue('0.11')
  v0_11,
  @JsonValue('0.0.80')
  v0_0_80,
  @JsonValue('0.0.81')
  v0_0_81,
  @JsonValue('0.0.82')
  v0_0_82,
  @JsonValue('0.4.0')
  v0_4_0,
  @JsonValue('0.5.0')
  v0_5_0,
  @JsonValue('1.0.0')
  v1_0_0,
  @JsonValue('1.0.1')
  v1_0_1,
  @JsonValue('1.0.2')
  v1_0_2,
  @JsonValue('1.1.0')
  v1_1_0,
  @JsonValue('1.4.0')
  v1_4_0,
  @JsonValue('1.6.0')
  v1_6_0,
  @JsonValue('1.8.0')
  v1_8_0,
  @JsonValue('3.0.0')
  v3_0_0,
  @JsonValue('3.0.1')
  v3_0_1,
  @JsonValue('3.3.0')
  v3_3_0,
  @JsonValue('3.5.0')
  v3_5_0,
  @JsonValue('4.0.0')
  v4_0_0,
  @JsonValue('4.0.1')
  v4_0_1,
  @JsonValue('unknown')
  unknown,
}

enum StructureDefinitionKind {
  @JsonValue('primitive-type')
  primitive_type,
  @JsonValue('complex-type')
  complex_type,
  @JsonValue('resource')
  resource,
  @JsonValue('logical')
  logical,
  @JsonValue('unknown')
  unknown,
}

enum StructureDefinitionDerivation {
  @JsonValue('specialization')
  specialization,
  @JsonValue('constraint')
  constraint,
  @JsonValue('unknown')
  unknown,
}

enum StructureDefinitionContextType {
  @JsonValue('fhirpath')
  fhirpath,
  @JsonValue('element')
  element,
  @JsonValue('extension')
  extension,
  @JsonValue('unknown')
  unknown,
}
