create table if not exists internal.accountsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "owner" jsonb,
  "patient" jsonb,
  "period" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "type" jsonb
);

create table if not exists internal.activitydefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.administrableproductdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "device" jsonb,
  "dose-form" jsonb,
  "form-of" jsonb,
  "identifier" jsonb,
  "ingredient" jsonb,
  "manufactured-item" jsonb,
  "route" jsonb,
  "target-species" jsonb
);

create table if not exists internal.adverseeventsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "actuality" jsonb,
  "category" jsonb,
  "date" jsonb,
  "event" jsonb,
  "location" jsonb,
  "recorder" jsonb,
  "resultingcondition" jsonb,
  "seriousness" jsonb,
  "severity" jsonb,
  "study" jsonb,
  "subject" jsonb,
  "substance" jsonb
);

create table if not exists internal.allergyintolerancesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "asserter" jsonb,
  "category" jsonb,
  "clinical-status" jsonb,
  "code" jsonb,
  "criticality" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "last-date" jsonb,
  "manifestation" jsonb,
  "onset" jsonb,
  "patient" jsonb,
  "recorder" jsonb,
  "route" jsonb,
  "severity" jsonb,
  "type" jsonb,
  "verification-status" jsonb
);

create table if not exists internal.conditionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "abatement-age" jsonb,
  "abatement-date" jsonb,
  "abatement-string" jsonb,
  "asserter" jsonb,
  "body-site" jsonb,
  "category" jsonb,
  "clinical-status" jsonb,
  "encounter" jsonb,
  "evidence" jsonb,
  "evidence-detail" jsonb,
  "onset-age" jsonb,
  "onset-date" jsonb,
  "onset-info" jsonb,
  "recorded-date" jsonb,
  "severity" jsonb,
  "stage" jsonb,
  "subject" jsonb,
  "verification-status" jsonb
);

create table if not exists internal.devicerequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "authored-on" jsonb,
  "based-on" jsonb,
  "device" jsonb,
  "event-date" jsonb,
  "group-identifier" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "insurance" jsonb,
  "intent" jsonb,
  "performer" jsonb,
  "prior-request" jsonb,
  "requester" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.diagnosticreportsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "based-on" jsonb,
  "category" jsonb,
  "conclusion" jsonb,
  "issued" jsonb,
  "media" jsonb,
  "performer" jsonb,
  "result" jsonb,
  "results-interpreter" jsonb,
  "specimen" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.familymemberhistorysearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "relationship" jsonb,
  "sex" jsonb,
  "status" jsonb
);

create table if not exists internal.listsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "empty-reason" jsonb,
  "item" jsonb,
  "notes" jsonb,
  "source" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "title" jsonb
);

create table if not exists internal.medicationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "expiration-date" jsonb,
  "form" jsonb,
  "identifier" jsonb,
  "ingredient" jsonb,
  "ingredient-code" jsonb,
  "lot-number" jsonb,
  "manufacturer" jsonb,
  "status" jsonb
);

create table if not exists internal.medicationadministrationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "context" jsonb,
  "device" jsonb,
  "effective-time" jsonb,
  "medication" jsonb,
  "performer" jsonb,
  "reason-given" jsonb,
  "reason-not-given" jsonb,
  "request" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.medicationdispensesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "medication" jsonb,
  "status" jsonb,
  "context" jsonb,
  "destination" jsonb,
  "performer" jsonb,
  "prescription" jsonb,
  "receiver" jsonb,
  "responsibleparty" jsonb,
  "subject" jsonb,
  "type" jsonb,
  "whenhandedover" jsonb,
  "whenprepared" jsonb
);

create table if not exists internal.medicationrequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "medication" jsonb,
  "status" jsonb,
  "authoredon" jsonb,
  "category" jsonb,
  "date" jsonb,
  "encounter" jsonb,
  "intended-dispenser" jsonb,
  "intended-performer" jsonb,
  "intended-performertype" jsonb,
  "intent" jsonb,
  "priority" jsonb,
  "requester" jsonb,
  "subject" jsonb
);

create table if not exists internal.medicationstatementsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "medication" jsonb,
  "status" jsonb,
  "category" jsonb,
  "context" jsonb,
  "effective" jsonb,
  "part-of" jsonb,
  "source" jsonb,
  "subject" jsonb
);

create table if not exists internal.observationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "based-on" jsonb,
  "category" jsonb,
  "combo-code" jsonb,
  "combo-data-absent-reason" jsonb,
  "combo-value-concept" jsonb,
  "combo-value-quantity" jsonb,
  "component-code" jsonb,
  "component-data-absent-reason" jsonb,
  "component-value-concept" jsonb,
  "component-value-quantity" jsonb,
  "data-absent-reason" jsonb,
  "derived-from" jsonb,
  "device" jsonb,
  "focus" jsonb,
  "has-member" jsonb,
  "method" jsonb,
  "part-of" jsonb,
  "performer" jsonb,
  "specimen" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "value-concept" jsonb,
  "value-date" jsonb,
  "value-quantity" jsonb,
  "value-string" jsonb,
  "code-value-concept" jsonb,
  "code-value-date" jsonb,
  "code-value-quantity" jsonb,
  "code-value-string" jsonb,
  "combo-code-value-concept" jsonb,
  "combo-code-value-quantity" jsonb,
  "component-code-value-concept" jsonb,
  "component-code-value-quantity" jsonb
);

create table if not exists internal.proceduresearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "based-on" jsonb,
  "category" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "location" jsonb,
  "part-of" jsonb,
  "performer" jsonb,
  "reason-code" jsonb,
  "reason-reference" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.servicerequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "authored" jsonb,
  "based-on" jsonb,
  "body-site" jsonb,
  "category" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "intent" jsonb,
  "occurrence" jsonb,
  "performer" jsonb,
  "performer-type" jsonb,
  "priority" jsonb,
  "replaces" jsonb,
  "requester" jsonb,
  "requisition" jsonb,
  "specimen" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.careplansearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "activity-code" jsonb,
  "activity-date" jsonb,
  "activity-reference" jsonb,
  "based-on" jsonb,
  "care-team" jsonb,
  "category" jsonb,
  "condition" jsonb,
  "encounter" jsonb,
  "goal" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "intent" jsonb,
  "part-of" jsonb,
  "performer" jsonb,
  "replaces" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.careteamsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "category" jsonb,
  "encounter" jsonb,
  "participant" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.clinicalimpressionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "patient" jsonb,
  "assessor" jsonb,
  "encounter" jsonb,
  "finding-code" jsonb,
  "finding-ref" jsonb,
  "identifier" jsonb,
  "investigation" jsonb,
  "previous" jsonb,
  "problem" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "supporting-info" jsonb
);

create table if not exists internal.compositionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "type" jsonb,
  "attester" jsonb,
  "author" jsonb,
  "category" jsonb,
  "confidentiality" jsonb,
  "context" jsonb,
  "encounter" jsonb,
  "entry" jsonb,
  "period" jsonb,
  "related-id" jsonb,
  "related-ref" jsonb,
  "section" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "title" jsonb
);

create table if not exists internal.consentsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "action" jsonb,
  "actor" jsonb,
  "category" jsonb,
  "consentor" jsonb,
  "data" jsonb,
  "organization" jsonb,
  "period" jsonb,
  "purpose" jsonb,
  "scope" jsonb,
  "security-label" jsonb,
  "source-reference" jsonb,
  "status" jsonb
);

create table if not exists internal.encountersearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "type" jsonb,
  "account" jsonb,
  "appointment" jsonb,
  "based-on" jsonb,
  "class" jsonb,
  "diagnosis" jsonb,
  "episode-of-care" jsonb,
  "length" jsonb,
  "location" jsonb,
  "location-period" jsonb,
  "part-of" jsonb,
  "participant" jsonb,
  "participant-type" jsonb,
  "practitioner" jsonb,
  "reason-code" jsonb,
  "reason-reference" jsonb,
  "service-provider" jsonb,
  "special-arrangement" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.episodeofcaresearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "type" jsonb,
  "care-manager" jsonb,
  "condition" jsonb,
  "incoming-referral" jsonb,
  "organization" jsonb,
  "status" jsonb
);

create table if not exists internal.flagsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "author" jsonb,
  "identifier" jsonb,
  "subject" jsonb
);

create table if not exists internal.immunizationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "location" jsonb,
  "lot-number" jsonb,
  "manufacturer" jsonb,
  "performer" jsonb,
  "reaction" jsonb,
  "reaction-date" jsonb,
  "reason-code" jsonb,
  "reason-reference" jsonb,
  "series" jsonb,
  "status" jsonb,
  "status-reason" jsonb,
  "target-disease" jsonb,
  "vaccine-code" jsonb
);

create table if not exists internal.riskassessmentsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "condition" jsonb,
  "method" jsonb,
  "performer" jsonb,
  "probability" jsonb,
  "risk" jsonb,
  "subject" jsonb
);

create table if not exists internal.supplyrequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "category" jsonb,
  "requester" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "supplier" jsonb
);

create table if not exists internal.detectedissuesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "author" jsonb,
  "code" jsonb,
  "identified" jsonb,
  "implicated" jsonb
);

create table if not exists internal.documentmanifestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "type" jsonb,
  "author" jsonb,
  "created" jsonb,
  "description" jsonb,
  "item" jsonb,
  "recipient" jsonb,
  "related-id" jsonb,
  "related-ref" jsonb,
  "source" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.documentreferencesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "type" jsonb,
  "encounter" jsonb,
  "authenticator" jsonb,
  "author" jsonb,
  "category" jsonb,
  "contenttype" jsonb,
  "custodian" jsonb,
  "date" jsonb,
  "description" jsonb,
  "event" jsonb,
  "facility" jsonb,
  "format" jsonb,
  "language" jsonb,
  "location" jsonb,
  "period" jsonb,
  "related" jsonb,
  "relatesto" jsonb,
  "relation" jsonb,
  "security-label" jsonb,
  "setting" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "relationship" jsonb
);

create table if not exists internal.goalsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "achievement-status" jsonb,
  "category" jsonb,
  "lifecycle-status" jsonb,
  "start-date" jsonb,
  "subject" jsonb,
  "target-date" jsonb
);

create table if not exists internal.imagingstudysearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "basedon" jsonb,
  "bodysite" jsonb,
  "dicom-class" jsonb,
  "encounter" jsonb,
  "endpoint" jsonb,
  "instance" jsonb,
  "interpreter" jsonb,
  "modality" jsonb,
  "performer" jsonb,
  "reason" jsonb,
  "referrer" jsonb,
  "series" jsonb,
  "started" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.nutritionordersearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "additive" jsonb,
  "datetime" jsonb,
  "formula" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "oraldiet" jsonb,
  "provider" jsonb,
  "status" jsonb,
  "supplement" jsonb
);

create table if not exists internal.supplydeliverysearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "receiver" jsonb,
  "status" jsonb,
  "supplier" jsonb
);

create table if not exists internal.visionprescriptionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "encounter" jsonb,
  "datewritten" jsonb,
  "prescriber" jsonb,
  "status" jsonb
);

create table if not exists internal.deviceusestatementsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "patient" jsonb,
  "device" jsonb,
  "identifier" jsonb,
  "subject" jsonb
);

create table if not exists internal.appointmentsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "actor" jsonb,
  "appointment-type" jsonb,
  "based-on" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "part-status" jsonb,
  "patient" jsonb,
  "practitioner" jsonb,
  "reason-code" jsonb,
  "reason-reference" jsonb,
  "service-category" jsonb,
  "service-type" jsonb,
  "slot" jsonb,
  "specialty" jsonb,
  "status" jsonb,
  "supporting-info" jsonb
);

create table if not exists internal.appointmentresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "actor" jsonb,
  "appointment" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "part-status" jsonb,
  "patient" jsonb,
  "practitioner" jsonb
);

create table if not exists internal.auditeventsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "action" jsonb,
  "address" jsonb,
  "agent" jsonb,
  "agent-name" jsonb,
  "agent-role" jsonb,
  "altid" jsonb,
  "date" jsonb,
  "entity" jsonb,
  "entity-name" jsonb,
  "entity-role" jsonb,
  "entity-type" jsonb,
  "outcome" jsonb,
  "patient" jsonb,
  "policy" jsonb,
  "site" jsonb,
  "source" jsonb,
  "subtype" jsonb,
  "type" jsonb
);

create table if not exists internal.basicsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "author" jsonb,
  "code" jsonb,
  "created" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "subject" jsonb
);

create table if not exists internal.bodystructuresearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "morphology" jsonb,
  "patient" jsonb
);

create table if not exists internal.bundlesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composition" jsonb,
  "identifier" jsonb,
  "message" jsonb,
  "timestamp" jsonb,
  "type" jsonb
);

create table if not exists internal.capabilitystatementsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "fhirversion" jsonb,
  "format" jsonb,
  "guide" jsonb,
  "jurisdiction" jsonb,
  "mode" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "resource" jsonb,
  "resource-profile" jsonb,
  "security-service" jsonb,
  "software" jsonb,
  "status" jsonb,
  "supported-profile" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.codesystemsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "code" jsonb,
  "content-mode" jsonb,
  "identifier" jsonb,
  "language" jsonb,
  "supplements" jsonb,
  "system" jsonb
);

create table if not exists internal.compartmentdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "code" jsonb,
  "resource" jsonb
);

create table if not exists internal.conceptmapsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "identifier" jsonb,
  "dependson" jsonb,
  "other" jsonb,
  "product" jsonb,
  "source" jsonb,
  "source-code" jsonb,
  "source-system" jsonb,
  "source-uri" jsonb,
  "target" jsonb,
  "target-code" jsonb,
  "target-system" jsonb,
  "target-uri" jsonb
);

create table if not exists internal.graphdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "start" jsonb
);

create table if not exists internal.implementationguidesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "depends-on" jsonb,
  "experimental" jsonb,
  "global" jsonb,
  "resource" jsonb
);

create table if not exists internal.messagedefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "identifier" jsonb,
  "category" jsonb,
  "event" jsonb,
  "focus" jsonb,
  "parent" jsonb
);

create table if not exists internal.namingsystemsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "contact" jsonb,
  "id-type" jsonb,
  "kind" jsonb,
  "period" jsonb,
  "responsible" jsonb,
  "telecom" jsonb,
  "type" jsonb,
  "value" jsonb
);

create table if not exists internal.operationdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "base" jsonb,
  "code" jsonb,
  "input-profile" jsonb,
  "instance" jsonb,
  "kind" jsonb,
  "output-profile" jsonb,
  "system" jsonb,
  "type" jsonb
);

create table if not exists internal.searchparametersearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "base" jsonb,
  "code" jsonb,
  "component" jsonb,
  "derived-from" jsonb,
  "target" jsonb,
  "type" jsonb
);

create table if not exists internal.structuredefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "identifier" jsonb,
  "abstract" jsonb,
  "base" jsonb,
  "base-path" jsonb,
  "derivation" jsonb,
  "experimental" jsonb,
  "ext-context" jsonb,
  "keyword" jsonb,
  "kind" jsonb,
  "path" jsonb,
  "type" jsonb,
  "valueset" jsonb
);

create table if not exists internal.structuremapsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "identifier" jsonb
);

create table if not exists internal.terminologycapabilitiessearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.valuesetsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb,
  "identifier" jsonb,
  "code" jsonb,
  "expansion" jsonb,
  "reference" jsonb
);

create table if not exists internal.chargeitemsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "account" jsonb,
  "code" jsonb,
  "context" jsonb,
  "entered-date" jsonb,
  "enterer" jsonb,
  "factor-override" jsonb,
  "identifier" jsonb,
  "occurrence" jsonb,
  "patient" jsonb,
  "performer-actor" jsonb,
  "performer-function" jsonb,
  "performing-organization" jsonb,
  "price-override" jsonb,
  "quantity" jsonb,
  "requesting-organization" jsonb,
  "service" jsonb,
  "subject" jsonb
);

create table if not exists internal.chargeitemdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.citationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.claimsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "care-team" jsonb,
  "created" jsonb,
  "detail-udi" jsonb,
  "encounter" jsonb,
  "enterer" jsonb,
  "facility" jsonb,
  "identifier" jsonb,
  "insurer" jsonb,
  "item-udi" jsonb,
  "patient" jsonb,
  "payee" jsonb,
  "priority" jsonb,
  "procedure-udi" jsonb,
  "provider" jsonb,
  "status" jsonb,
  "subdetail-udi" jsonb,
  "use" jsonb
);

create table if not exists internal.claimresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "created" jsonb,
  "disposition" jsonb,
  "identifier" jsonb,
  "insurer" jsonb,
  "outcome" jsonb,
  "patient" jsonb,
  "payment-date" jsonb,
  "request" jsonb,
  "requestor" jsonb,
  "status" jsonb,
  "use" jsonb
);

create table if not exists internal.clinicalusedefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "contraindication" jsonb,
  "contraindication-reference" jsonb,
  "effect" jsonb,
  "effect-reference" jsonb,
  "identifier" jsonb,
  "indication" jsonb,
  "indication-reference" jsonb,
  "interaction" jsonb,
  "product" jsonb,
  "subject" jsonb,
  "type" jsonb
);

create table if not exists internal.communicationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "based-on" jsonb,
  "category" jsonb,
  "encounter" jsonb,
  "identifier" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "medium" jsonb,
  "part-of" jsonb,
  "patient" jsonb,
  "received" jsonb,
  "recipient" jsonb,
  "sender" jsonb,
  "sent" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.communicationrequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "authored" jsonb,
  "based-on" jsonb,
  "category" jsonb,
  "encounter" jsonb,
  "group-identifier" jsonb,
  "identifier" jsonb,
  "medium" jsonb,
  "occurrence" jsonb,
  "patient" jsonb,
  "priority" jsonb,
  "recipient" jsonb,
  "replaces" jsonb,
  "requester" jsonb,
  "sender" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.contractsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "authority" jsonb,
  "domain" jsonb,
  "identifier" jsonb,
  "instantiates" jsonb,
  "issued" jsonb,
  "patient" jsonb,
  "signer" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "url" jsonb
);

create table if not exists internal.coveragesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "beneficiary" jsonb,
  "class-type" jsonb,
  "class-value" jsonb,
  "dependent" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "payor" jsonb,
  "policy-holder" jsonb,
  "status" jsonb,
  "subscriber" jsonb,
  "type" jsonb
);

create table if not exists internal.coverageeligibilityrequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "created" jsonb,
  "enterer" jsonb,
  "facility" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "provider" jsonb,
  "status" jsonb
);

create table if not exists internal.coverageeligibilityresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "created" jsonb,
  "disposition" jsonb,
  "identifier" jsonb,
  "insurer" jsonb,
  "outcome" jsonb,
  "patient" jsonb,
  "request" jsonb,
  "requestor" jsonb,
  "status" jsonb
);

create table if not exists internal.devicesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "device-name" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "manufacturer" jsonb,
  "model" jsonb,
  "organization" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "type" jsonb,
  "udi-carrier" jsonb,
  "udi-di" jsonb,
  "url" jsonb
);

create table if not exists internal.devicedefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "parent" jsonb,
  "type" jsonb
);

create table if not exists internal.devicemetricsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "category" jsonb,
  "identifier" jsonb,
  "parent" jsonb,
  "source" jsonb,
  "type" jsonb
);

create table if not exists internal.endpointsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "connection-type" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "organization" jsonb,
  "payload-type" jsonb,
  "status" jsonb
);

create table if not exists internal.enrollmentrequestsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.enrollmentresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "request" jsonb,
  "status" jsonb
);

create table if not exists internal.eventdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.evidencesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "identifier" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.evidencereportsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "identifier" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "url" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.evidencevariablesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.examplescenariosearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.explanationofbenefitsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "care-team" jsonb,
  "claim" jsonb,
  "coverage" jsonb,
  "created" jsonb,
  "detail-udi" jsonb,
  "disposition" jsonb,
  "encounter" jsonb,
  "enterer" jsonb,
  "facility" jsonb,
  "identifier" jsonb,
  "item-udi" jsonb,
  "patient" jsonb,
  "payee" jsonb,
  "procedure-udi" jsonb,
  "provider" jsonb,
  "status" jsonb,
  "subdetail-udi" jsonb
);

create table if not exists internal.groupsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "actual" jsonb,
  "characteristic" jsonb,
  "code" jsonb,
  "exclude" jsonb,
  "identifier" jsonb,
  "managing-entity" jsonb,
  "member" jsonb,
  "type" jsonb,
  "value" jsonb,
  "characteristic-value" jsonb
);

create table if not exists internal.guidanceresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "request" jsonb,
  "subject" jsonb
);

create table if not exists internal.healthcareservicesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "active" jsonb,
  "characteristic" jsonb,
  "coverage-area" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "name" jsonb,
  "organization" jsonb,
  "program" jsonb,
  "service-category" jsonb,
  "service-type" jsonb,
  "specialty" jsonb
);

create table if not exists internal.immunizationevaluationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "dose-status" jsonb,
  "identifier" jsonb,
  "immunization-event" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "target-disease" jsonb
);

create table if not exists internal.immunizationrecommendationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "information" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "support" jsonb,
  "target-disease" jsonb,
  "vaccine-type" jsonb
);

create table if not exists internal.ingredientsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "for" jsonb,
  "function" jsonb,
  "identifier" jsonb,
  "manufacturer" jsonb,
  "role" jsonb,
  "substance" jsonb,
  "substance-code" jsonb,
  "substance-definition" jsonb
);

create table if not exists internal.insuranceplansearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "administered-by" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "owned-by" jsonb,
  "phonetic" jsonb,
  "status" jsonb,
  "type" jsonb
);

create table if not exists internal.invoicesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "account" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "issuer" jsonb,
  "participant" jsonb,
  "participant-role" jsonb,
  "patient" jsonb,
  "recipient" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "totalgross" jsonb,
  "totalnet" jsonb,
  "type" jsonb
);

create table if not exists internal.librarysearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "content-type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "type" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.linkagesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "author" jsonb,
  "item" jsonb,
  "source" jsonb
);

create table if not exists internal.locationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "near" jsonb,
  "operational-status" jsonb,
  "organization" jsonb,
  "partof" jsonb,
  "status" jsonb,
  "type" jsonb
);

create table if not exists internal.manufactureditemdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "dose-form" jsonb,
  "identifier" jsonb,
  "ingredient" jsonb
);

create table if not exists internal.measuresearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.measurereportsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "evaluated-resource" jsonb,
  "identifier" jsonb,
  "measure" jsonb,
  "patient" jsonb,
  "period" jsonb,
  "reporter" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.mediasearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "based-on" jsonb,
  "created" jsonb,
  "device" jsonb,
  "encounter" jsonb,
  "identifier" jsonb,
  "modality" jsonb,
  "operator" jsonb,
  "patient" jsonb,
  "site" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "type" jsonb,
  "view" jsonb
);

create table if not exists internal.medicationknowledgesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "classification" jsonb,
  "classification-type" jsonb,
  "code" jsonb,
  "doseform" jsonb,
  "ingredient" jsonb,
  "ingredient-code" jsonb,
  "manufacturer" jsonb,
  "monitoring-program-name" jsonb,
  "monitoring-program-type" jsonb,
  "monograph" jsonb,
  "monograph-type" jsonb,
  "source-cost" jsonb,
  "status" jsonb
);

create table if not exists internal.medicinalproductdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "characteristic" jsonb,
  "characteristic-type" jsonb,
  "contact" jsonb,
  "domain" jsonb,
  "identifier" jsonb,
  "ingredient" jsonb,
  "master-file" jsonb,
  "name" jsonb,
  "name-language" jsonb,
  "product-classification" jsonb,
  "status" jsonb,
  "type" jsonb
);

create table if not exists internal.messageheadersearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "author" jsonb,
  "code" jsonb,
  "destination" jsonb,
  "destination-uri" jsonb,
  "enterer" jsonb,
  "event" jsonb,
  "focus" jsonb,
  "receiver" jsonb,
  "response-id" jsonb,
  "responsible" jsonb,
  "sender" jsonb,
  "source" jsonb,
  "source-uri" jsonb,
  "target" jsonb
);

create table if not exists internal.molecularsequencesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "chromosome" jsonb,
  "identifier" jsonb,
  "patient" jsonb,
  "referenceseqid" jsonb,
  "type" jsonb,
  "variant-end" jsonb,
  "variant-start" jsonb,
  "window-end" jsonb,
  "window-start" jsonb,
  "chromosome-variant-coordinate" jsonb,
  "chromosome-window-coordinate" jsonb,
  "referenceseqid-variant-coordinate" jsonb,
  "referenceseqid-window-coordinate" jsonb
);

create table if not exists internal.nutritionproductsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "status" jsonb
);

create table if not exists internal.organizationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "active" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "partof" jsonb,
  "phonetic" jsonb,
  "type" jsonb
);

create table if not exists internal.organizationaffiliationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "active" jsonb,
  "date" jsonb,
  "email" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "network" jsonb,
  "participating-organization" jsonb,
  "phone" jsonb,
  "primary-organization" jsonb,
  "role" jsonb,
  "service" jsonb,
  "specialty" jsonb,
  "telecom" jsonb
);

create table if not exists internal.packagedproductdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "biological" jsonb,
  "contained-item" jsonb,
  "device" jsonb,
  "identifier" jsonb,
  "manufactured-item" jsonb,
  "medication" jsonb,
  "name" jsonb,
  "nutrition" jsonb,
  "package" jsonb,
  "package-for" jsonb,
  "status" jsonb
);

create table if not exists internal.patientsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "active" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "birthdate" jsonb,
  "death-date" jsonb,
  "deceased" jsonb,
  "email" jsonb,
  "family" jsonb,
  "gender" jsonb,
  "general-practitioner" jsonb,
  "given" jsonb,
  "identifier" jsonb,
  "language" jsonb,
  "link" jsonb,
  "name" jsonb,
  "organization" jsonb,
  "phone" jsonb,
  "phonetic" jsonb,
  "telecom" jsonb
);

create table if not exists internal.personsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "birthdate" jsonb,
  "email" jsonb,
  "gender" jsonb,
  "phone" jsonb,
  "phonetic" jsonb,
  "telecom" jsonb,
  "identifier" jsonb,
  "link" jsonb,
  "name" jsonb,
  "organization" jsonb,
  "patient" jsonb,
  "practitioner" jsonb,
  "relatedperson" jsonb
);

create table if not exists internal.practitionersearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "email" jsonb,
  "family" jsonb,
  "gender" jsonb,
  "given" jsonb,
  "phone" jsonb,
  "phonetic" jsonb,
  "telecom" jsonb,
  "active" jsonb,
  "communication" jsonb,
  "identifier" jsonb,
  "name" jsonb
);

create table if not exists internal.relatedpersonsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "address" jsonb,
  "address-city" jsonb,
  "address-country" jsonb,
  "address-postalcode" jsonb,
  "address-state" jsonb,
  "address-use" jsonb,
  "birthdate" jsonb,
  "email" jsonb,
  "gender" jsonb,
  "phone" jsonb,
  "phonetic" jsonb,
  "telecom" jsonb,
  "active" jsonb,
  "identifier" jsonb,
  "name" jsonb,
  "patient" jsonb,
  "relationship" jsonb
);

create table if not exists internal.practitionerrolesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "email" jsonb,
  "phone" jsonb,
  "telecom" jsonb,
  "active" jsonb,
  "date" jsonb,
  "endpoint" jsonb,
  "identifier" jsonb,
  "location" jsonb,
  "organization" jsonb,
  "practitioner" jsonb,
  "role" jsonb,
  "service" jsonb,
  "specialty" jsonb
);

create table if not exists internal.paymentnoticesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "created" jsonb,
  "identifier" jsonb,
  "payment-status" jsonb,
  "provider" jsonb,
  "request" jsonb,
  "response" jsonb,
  "status" jsonb
);

create table if not exists internal.paymentreconciliationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "created" jsonb,
  "disposition" jsonb,
  "identifier" jsonb,
  "outcome" jsonb,
  "payment-issuer" jsonb,
  "request" jsonb,
  "requestor" jsonb,
  "status" jsonb
);

create table if not exists internal.plandefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "definition" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "type" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.provenancesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "agent" jsonb,
  "agent-role" jsonb,
  "agent-type" jsonb,
  "entity" jsonb,
  "location" jsonb,
  "patient" jsonb,
  "recorded" jsonb,
  "signature-type" jsonb,
  "target" jsonb,
  "when" jsonb
);

create table if not exists internal.questionnairesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "code" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "definition" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "subject-type" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.questionnaireresponsesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "author" jsonb,
  "authored" jsonb,
  "based-on" jsonb,
  "encounter" jsonb,
  "identifier" jsonb,
  "part-of" jsonb,
  "patient" jsonb,
  "questionnaire" jsonb,
  "source" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.regulatedauthorizationsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "case" jsonb,
  "case-type" jsonb,
  "holder" jsonb,
  "identifier" jsonb,
  "region" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.requestgroupsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "author" jsonb,
  "authored" jsonb,
  "code" jsonb,
  "encounter" jsonb,
  "group-identifier" jsonb,
  "identifier" jsonb,
  "instantiates-canonical" jsonb,
  "instantiates-uri" jsonb,
  "intent" jsonb,
  "participant" jsonb,
  "patient" jsonb,
  "priority" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.researchdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.researchelementdefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "composed-of" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "depends-on" jsonb,
  "derived-from" jsonb,
  "description" jsonb,
  "effective" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "predecessor" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "successor" jsonb,
  "title" jsonb,
  "topic" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.researchstudysearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "category" jsonb,
  "date" jsonb,
  "focus" jsonb,
  "identifier" jsonb,
  "keyword" jsonb,
  "location" jsonb,
  "partof" jsonb,
  "principalinvestigator" jsonb,
  "protocol" jsonb,
  "site" jsonb,
  "sponsor" jsonb,
  "status" jsonb,
  "title" jsonb
);

create table if not exists internal.researchsubjectsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "individual" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "study" jsonb
);

create table if not exists internal.schedulesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "active" jsonb,
  "actor" jsonb,
  "date" jsonb,
  "identifier" jsonb,
  "service-category" jsonb,
  "service-type" jsonb,
  "specialty" jsonb
);

create table if not exists internal.slotsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "appointment-type" jsonb,
  "identifier" jsonb,
  "schedule" jsonb,
  "service-category" jsonb,
  "service-type" jsonb,
  "specialty" jsonb,
  "start" jsonb,
  "status" jsonb
);

create table if not exists internal.specimensearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "accession" jsonb,
  "bodysite" jsonb,
  "collected" jsonb,
  "collector" jsonb,
  "container" jsonb,
  "container-id" jsonb,
  "identifier" jsonb,
  "parent" jsonb,
  "patient" jsonb,
  "status" jsonb,
  "subject" jsonb,
  "type" jsonb
);

create table if not exists internal.specimendefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "container" jsonb,
  "identifier" jsonb,
  "type" jsonb
);

create table if not exists internal.subscriptionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "contact" jsonb,
  "criteria" jsonb,
  "payload" jsonb,
  "status" jsonb,
  "type" jsonb,
  "url" jsonb
);

create table if not exists internal.subscriptiontopicsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "date" jsonb,
  "derived-or-self" jsonb,
  "identifier" jsonb,
  "resource" jsonb,
  "status" jsonb,
  "title" jsonb,
  "trigger-description" jsonb,
  "url" jsonb,
  "version" jsonb
);

create table if not exists internal.substancesearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "category" jsonb,
  "code" jsonb,
  "container-identifier" jsonb,
  "expiry" jsonb,
  "identifier" jsonb,
  "quantity" jsonb,
  "status" jsonb,
  "substance-reference" jsonb
);

create table if not exists internal.substancedefinitionsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "classification" jsonb,
  "code" jsonb,
  "domain" jsonb,
  "identifier" jsonb,
  "name" jsonb
);

create table if not exists internal.tasksearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "authored-on" jsonb,
  "based-on" jsonb,
  "business-status" jsonb,
  "code" jsonb,
  "encounter" jsonb,
  "focus" jsonb,
  "group-identifier" jsonb,
  "identifier" jsonb,
  "intent" jsonb,
  "modified" jsonb,
  "owner" jsonb,
  "part-of" jsonb,
  "patient" jsonb,
  "performer" jsonb,
  "period" jsonb,
  "priority" jsonb,
  "requester" jsonb,
  "status" jsonb,
  "subject" jsonb
);

create table if not exists internal.testreportsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "identifier" jsonb,
  "issued" jsonb,
  "participant" jsonb,
  "result" jsonb,
  "tester" jsonb,
  "testscript" jsonb
);

create table if not exists internal.testscriptsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "context" jsonb,
  "context-quantity" jsonb,
  "context-type" jsonb,
  "date" jsonb,
  "description" jsonb,
  "identifier" jsonb,
  "jurisdiction" jsonb,
  "name" jsonb,
  "publisher" jsonb,
  "status" jsonb,
  "testscript-capability" jsonb,
  "title" jsonb,
  "url" jsonb,
  "version" jsonb,
  "context-type-quantity" jsonb,
  "context-type-value" jsonb
);

create table if not exists internal.verificationresultsearch (
  id text primary key,
  "_content" jsonb,
  "_filter" jsonb,
  "_has" jsonb,
  "_id" jsonb,
  "_lastUpdated" jsonb,
  "_list" jsonb,
  "_profile" jsonb,
  "_query" jsonb,
  "_security" jsonb,
  "_source" jsonb,
  "_tag" jsonb,
  "_text" jsonb,
  "_type" jsonb,
  "target" jsonb
);