import 'functions.dart';

final functionNames = {
  '.empty': empty,
  '.exists': exists,
  '.all': () {},
  '.allTrue': () {},
  '.anyTrue': () {},
  '.allFalse': () {},
  '.anyFalse': () {},
  '.subsetOf': () {},
  '.supersetOf': () {},
  '.count': count,
  '.distinct': distinct,
  '.isDistinct': () {},
  '.where': () {},
  '.select': () {},
  '.repeat': () {},
  '.ofType': () {},
  '.single': () {},
  '.first': () {},
  '.last': () {},
  '.tail': () {},
  '.skip': () {},
  '.take': () {},
  '.intersect': () {},
  '.exclude': () {},
  '.union': () {},
  '.combine': () {},
  '.iif': () {},
  '.toBoolean': () {},
  '.convertsToBoolean': () {},
  '.toInteger': () {},
  '.convertsToInteger': () {},
  '.toDate': () {},
  '.convertsToDate': () {},
  '.toDateTime': () {},
  '.convertsToDateTime': () {},
  '.toDecimal': () {},
  '.convertsToDecimal': () {},
  '.toQuantity': () {},
  '.convertsToQuantity': () {},
  '.toString': () {},
  '.convertsToString': () {},
  '.toTime': () {},
  '.convertsToTime': () {},
  '.indexOf': () {},
  '.substring': () {},
  '.startsWith': () {},
  '.endsWith': () {},
  '.contains': () {},
  '.upper': () {},
  '.lower': () {},
  '.replace': () {},
  '.matches': () {},
  '.replaceMatches': () {},
  '.length': () {},
  '.toChars': () {},
  '.abs': () {},
  '.ceiling': () {},
  '.exp': () {},
  '.floor': () {},
  '.ln': () {},
  '.log': () {},
  '.power': () {},
  '.round': () {},
  '.sqrt': () {},
  '.truncate': () {},
  '.children': () {},
  '.descendants': () {},
  '.trace': () {},
  '.now': () {},
  '.timeOfDay': () {},
  '.today': () {},
  '.not': () {},
};
