import 'element.dart';

import 'DomainResource/account.dart';
import 'DomainResource/activityDefinition.dart';
import 'DomainResource/adverseEvent.dart';
import 'DomainResource/allergyIntolerance.dart';
import 'DomainResource/appointment.dart';
import 'DomainResource/appointmentResponse.dart';
import 'DomainResource/auditEvent.dart';
import 'DomainResource/basic.dart';
import 'DomainResource/bodySite.dart';
import 'DomainResource/capabilityStatement.dart';
import 'DomainResource/carePlan.dart';
import 'DomainResource/careTeam.dart';
import 'DomainResource/chargeItem.dart';
import 'DomainResource/claim.dart';
import 'DomainResource/claimResponse.dart';
import 'DomainResource/clinicalImpression.dart';
import 'DomainResource/codeSystem.dart';
import 'DomainResource/communication.dart';
import 'DomainResource/communicationRequest.dart';
import 'DomainResource/compartmentDefinition.dart';
import 'DomainResource/composition.dart';
import 'DomainResource/conceptMap.dart';
import 'DomainResource/condition.dart';
import 'DomainResource/consent.dart';
import 'DomainResource/contract.dart';
import 'DomainResource/coverage.dart';
import 'DomainResource/dataElement.dart';
import 'DomainResource/detectedIssue.dart';
import 'DomainResource/device.dart';
import 'DomainResource/deviceComponent.dart';
import 'DomainResource/deviceMetric.dart';
import 'DomainResource/deviceRequest.dart';
import 'DomainResource/deviceUseStatement.dart';
import 'DomainResource/diagnosticReport.dart';
import 'DomainResource/documentManifest.dart';
import 'DomainResource/documentReference.dart';
import 'DomainResource/eligibilityRequest.dart';
import 'DomainResource/eligibilityResponse.dart';
import 'DomainResource/encounter.dart';
import 'DomainResource/endpoint.dart';
import 'DomainResource/enrollmentRequest.dart';
import 'DomainResource/enrollmentResponse.dart';
import 'DomainResource/episodeOfCare.dart';
import 'DomainResource/expansionProfile.dart';
import 'DomainResource/explanationOfBenefit.dart';
import 'DomainResource/familyMemberHistory.dart';
import 'DomainResource/flag.dart';
import 'DomainResource/goal.dart';
import 'DomainResource/graphDefinition.dart';
import 'DomainResource/group.dart';
import 'DomainResource/guidanceResponse.dart';
import 'DomainResource/healthcareService.dart';
import 'DomainResource/imagingManifest.dart';
import 'DomainResource/imagingStudy.dart';
import 'DomainResource/immunization.dart';
import 'DomainResource/immunizationRecommendation.dart';
import 'DomainResource/implementationGuide.dart';
import 'DomainResource/library.dart';
import 'DomainResource/linkage.dart';
import 'DomainResource/lists.dart';
import 'DomainResource/location.dart';
import 'DomainResource/measure.dart';
import 'DomainResource/measureReport.dart';
import 'DomainResource/media.dart';
import 'DomainResource/medication.dart';
import 'DomainResource/medicationAdministration.dart';
import 'DomainResource/medicationDispense.dart';
import 'DomainResource/medicationRequest.dart';
import 'DomainResource/medicationStatement.dart';
import 'DomainResource/messageDefinition.dart';
import 'DomainResource/messageHeader.dart';
import 'DomainResource/namingSystem.dart';
import 'DomainResource/nutritionOrder.dart';
import 'DomainResource/observation.dart';
import 'DomainResource/operationDefinition.dart';
import 'DomainResource/operationOutcome.dart';
import 'DomainResource/organization.dart';
import 'DomainResource/patient.dart';
import 'DomainResource/paymentNotice.dart';
import 'DomainResource/paymentReconciliation.dart';
import 'DomainResource/person.dart';
import 'DomainResource/planDefinition.dart';
import 'DomainResource/practitioner.dart';
import 'DomainResource/practitionerRole.dart';
import 'DomainResource/procedure.dart';
import 'DomainResource/procedureRequest.dart';
import 'DomainResource/processRequest.dart';
import 'DomainResource/processResponse.dart';
import 'DomainResource/provenance.dart';
import 'DomainResource/questionnaire.dart';
import 'DomainResource/questionnaireResponse.dart';
import 'DomainResource/referralRequest.dart';
import 'DomainResource/relatedPerson.dart';
import 'DomainResource/requestGroup.dart';
import 'DomainResource/researchStudy.dart';
import 'DomainResource/researchSubject.dart';
import 'DomainResource/riskAssessment.dart';
import 'DomainResource/schedule.dart';
import 'DomainResource/searchParameter.dart';
import 'DomainResource/sequence.dart';
import 'DomainResource/serviceDefinition.dart';
import 'DomainResource/slot.dart';
import 'DomainResource/specimen.dart';
import 'DomainResource/structureDefinition.dart';
import 'DomainResource/structureMap.dart';
import 'DomainResource/subscription.dart';
import 'DomainResource/substance.dart';
import 'DomainResource/supplyDelivery.dart';
import 'DomainResource/supplyRequest.dart';
import 'DomainResource/task.dart';
import 'DomainResource/testReport.dart';
import 'DomainResource/testScript.dart';
import 'DomainResource/valueSet.dart';
import 'DomainResource/visionPrescription.dart';

import 'Element/address.dart';
import 'Element/annotation.dart';
import 'Element/attachment.dart';
import 'Element/backboneElement.dart';
import 'Element/codeableConcept.dart';
import 'Element/coding.dart';
import 'Element/contactDetail.dart';
import 'Element/contactPoint.dart';
import 'Element/contributor.dart';
import 'Element/dataRequirement.dart';
import 'Element/dosage.dart';
import 'Element/elementDefinition.dart';
import 'Element/extension.dart';
import 'Element/humanName.dart';
import 'Element/identifier.dart';
import 'Element/meta.dart';
import 'Element/narrative.dart';
import 'Element/parameterDefinition.dart';
import 'Element/period.dart';
import 'Element/quantity.dart';
import 'Element/range.dart';
import 'Element/ratio.dart';
import 'Element/reference.dart';
import 'Element/relatedArtifact.dart';
import 'Element/resource.dart';
import 'Element/sampledData.dart';
import 'Element/signature.dart';
import 'Element/timing.dart';
import 'Element/triggerDefinition.dart';
import 'Element/usageContext.dart';

import 'Quantity/age.dart';
import 'Quantity/count.dart';
import 'Quantity/distance.dart';
import 'Quantity/duration.dart';
import 'Quantity/money.dart';

import 'Resource/binary.dart';
import 'Resource/bundle.dart';
import 'Resource/domainResource.dart';
import 'Resource/parameters.dart';


dynamic resourceList(Map<String, dynamic> json) {
  switch (json['resourceType']) {
    case 'Element':
      return Element.fromJson(json);
    case 'Extension':
      return Extension.fromJson(json);
    case 'BackboneElement':
      return BackboneElement.fromJson(json);
    case 'Narrative':
      return Narrative.fromJson(json);
    case 'Annotation':
      return Annotation.fromJson(json);
    case 'Attachment':
      return Attachment.fromJson(json);
    case 'Identifier':
      return Identifier.fromJson(json);
    case 'CodeableConcept':
      return CodeableConcept.fromJson(json);
    case 'Coding':
      return Coding.fromJson(json);
    case 'Quantity':
      return Quantity.fromJson(json);
    case 'Duration':
      return Duration.fromJson(json);
    case 'Distance':
      return Distance.fromJson(json);
    case 'Count':
      return Count.fromJson(json);
    case 'Money':
      return Money.fromJson(json);
    case 'Age':
      return Age.fromJson(json);
    case 'Range':
      return Range.fromJson(json);
    case 'Period':
      return Period.fromJson(json);
    case 'Ratio':
      return Ratio.fromJson(json);
    case 'Reference':
      return Reference.fromJson(json);
    case 'SampledData':
      return SampledData.fromJson(json);
    case 'Signature':
      return Signature.fromJson(json);
    case 'HumanName':
      return HumanName.fromJson(json);
    case 'Address':
      return Address.fromJson(json);
    case 'ContactPoint':
      return ContactPoint.fromJson(json);
    case 'Timing':
      return Timing.fromJson(json);
    case 'Meta':
      return Meta.fromJson(json);
    case 'ElementDefinition':
      return ElementDefinition.fromJson(json);
    case 'ContactDetail':
      return ContactDetail.fromJson(json);
    case 'Contributor':
      return Contributor.fromJson(json);
    case 'Dosage':
      return Dosage.fromJson(json);
    case 'RelatedArtifact':
      return RelatedArtifact.fromJson(json);
    case 'UsageContext':
      return UsageContext.fromJson(json);
    case 'DataRequirement':
      return DataRequirement.fromJson(json);
    case 'ParameterDefinition':
      return ParameterDefinition.fromJson(json);
    case 'TriggerDefinition':
      return TriggerDefinition.fromJson(json);
    case 'Account':
      return Account.fromJson(json);
    case 'ActivityDefinition':
      return ActivityDefinition.fromJson(json);
    case 'AdverseEvent':
      return AdverseEvent.fromJson(json);
    case 'AllergyIntolerance':
      return AllergyIntolerance.fromJson(json);
    case 'Appointment':
      return Appointment.fromJson(json);
    case 'AppointmentResponse':
      return AppointmentResponse.fromJson(json);
    case 'AuditEvent':
      return AuditEvent.fromJson(json);
    case 'Basic':
      return Basic.fromJson(json);
    case 'Binary':
      return Binary.fromJson(json);
    case 'BodySite':
      return BodySite.fromJson(json);
    case 'Bundle':
      return Bundle.fromJson(json);
    case 'CapabilityStatement':
      return CapabilityStatement.fromJson(json);
    case 'CarePlan':
      return CarePlan.fromJson(json);
    case 'CareTeam':
      return CareTeam.fromJson(json);
    case 'ChargeItem':
      return ChargeItem.fromJson(json);
    case 'Claim':
      return Claim.fromJson(json);
    case 'ClaimResponse':
      return ClaimResponse.fromJson(json);
    case 'ClinicalImpression':
      return ClinicalImpression.fromJson(json);
    case 'CodeSystem':
      return CodeSystem.fromJson(json);
    case 'Communication':
      return Communication.fromJson(json);
    case 'CommunicationRequest':
      return CommunicationRequest.fromJson(json);
    case 'CompartmentDefinition':
      return CompartmentDefinition.fromJson(json);
    case 'Composition':
      return Composition.fromJson(json);
    case 'ConceptMap':
      return ConceptMap.fromJson(json);
    case 'Condition':
      return Condition.fromJson(json);
    case 'Consent':
      return Consent.fromJson(json);
    case 'Contract':
      return Contract.fromJson(json);
    case 'Coverage':
      return Coverage.fromJson(json);
    case 'DataElement':
      return DataElement.fromJson(json);
    case 'DetectedIssue':
      return DetectedIssue.fromJson(json);
    case 'Device':
      return Device.fromJson(json);
    case 'DeviceComponent':
      return DeviceComponent.fromJson(json);
    case 'DeviceMetric':
      return DeviceMetric.fromJson(json);
    case 'DeviceRequest':
      return DeviceRequest.fromJson(json);
    case 'DeviceUseStatement':
      return DeviceUseStatement.fromJson(json);
    case 'DiagnosticReport':
      return DiagnosticReport.fromJson(json);
    case 'DocumentManifest':
      return DocumentManifest.fromJson(json);
    case 'DocumentReference':
      return DocumentReference.fromJson(json);
    case 'DomainResource':
      return DomainResource.fromJson(json);
    case 'EligibilityRequest':
      return EligibilityRequest.fromJson(json);
    case 'EligibilityResponse':
      return EligibilityResponse.fromJson(json);
    case 'Encounter':
      return Encounter.fromJson(json);
    case 'Endpoint':
      return Endpoint.fromJson(json);
    case 'EnrollmentRequest':
      return EnrollmentRequest.fromJson(json);
    case 'EnrollmentResponse':
      return EnrollmentResponse.fromJson(json);
    case 'EpisodeOfCare':
      return EpisodeOfCare.fromJson(json);
    case 'ExpansionProfile':
      return ExpansionProfile.fromJson(json);
    case 'ExplanationOfBenefit':
      return ExplanationOfBenefit.fromJson(json);
    case 'FamilyMemberHistory':
      return FamilyMemberHistory.fromJson(json);
    case 'Flag':
      return Flag.fromJson(json);
    case 'Goal':
      return Goal.fromJson(json);
    case 'GraphDefinition':
      return GraphDefinition.fromJson(json);
    case 'Group':
      return Group.fromJson(json);
    case 'GuidanceResponse':
      return GuidanceResponse.fromJson(json);
    case 'HealthcareService':
      return HealthcareService.fromJson(json);
    case 'ImagingManifest':
      return ImagingManifest.fromJson(json);
    case 'ImagingStudy':
      return ImagingStudy.fromJson(json);
    case 'Immunization':
      return Immunization.fromJson(json);
    case 'ImmunizationRecommendation':
      return ImmunizationRecommendation.fromJson(json);
    case 'ImplementationGuide':
      return ImplementationGuide.fromJson(json);
    case 'Library':
      return Library.fromJson(json);
    case 'Linkage':
      return Linkage.fromJson(json);
    case 'List':
      return Lists.fromJson(json);
    case 'Location':
      return Location.fromJson(json);
    case 'Measure':
      return Measure.fromJson(json);
    case 'MeasureReport':
      return MeasureReport.fromJson(json);
    case 'Media':
      return Media.fromJson(json);
    case 'Medication':
      return Medication.fromJson(json);
    case 'MedicationAdministration':
      return MedicationAdministration.fromJson(json);
    case 'MedicationDispense':
      return MedicationDispense.fromJson(json);
    case 'MedicationRequest':
      return MedicationRequest.fromJson(json);
    case 'MedicationStatement':
      return MedicationStatement.fromJson(json);
    case 'MessageDefinition':
      return MessageDefinition.fromJson(json);
    case 'MessageHeader':
      return MessageHeader.fromJson(json);
    case 'NamingSystem':
      return NamingSystem.fromJson(json);
    case 'NutritionOrder':
      return NutritionOrder.fromJson(json);
    case 'Observation':
      return Observation.fromJson(json);
    case 'OperationDefinition':
      return OperationDefinition.fromJson(json);
    case 'OperationOutcome':
      return OperationOutcome.fromJson(json);
    case 'Organization':
      return Organization.fromJson(json);
    case 'Parameters':
      return Parameters.fromJson(json);
    case 'Patient':
      return Patient.fromJson(json);
    case 'PaymentNotice':
      return PaymentNotice.fromJson(json);
    case 'PaymentReconciliation':
      return PaymentReconciliation.fromJson(json);
    case 'Person':
      return Person.fromJson(json);
    case 'PlanDefinition':
      return PlanDefinition.fromJson(json);
    case 'Practitioner':
      return Practitioner.fromJson(json);
    case 'PractitionerRole':
      return PractitionerRole.fromJson(json);
    case 'Procedure':
      return Procedure.fromJson(json);
    case 'ProcedureRequest':
      return ProcedureRequest.fromJson(json);
    case 'ProcessRequest':
      return ProcessRequest.fromJson(json);
    case 'ProcessResponse':
      return ProcessResponse.fromJson(json);
    case 'Provenance':
      return Provenance.fromJson(json);
    case 'Questionnaire':
      return Questionnaire.fromJson(json);
    case 'QuestionnaireResponse':
      return QuestionnaireResponse.fromJson(json);
    case 'ReferralRequest':
      return ReferralRequest.fromJson(json);
    case 'RelatedPerson':
      return RelatedPerson.fromJson(json);
    case 'RequestGroup':
      return RequestGroup.fromJson(json);
    case 'ResearchStudy':
      return ResearchStudy.fromJson(json);
    case 'ResearchSubject':
      return ResearchSubject.fromJson(json);
    case 'Resource':
      return Resource.fromJson(json);
    case 'RiskAssessment':
      return RiskAssessment.fromJson(json);
    case 'Schedule':
      return Schedule.fromJson(json);
    case 'SearchParameter':
      return SearchParameter.fromJson(json);
    case 'Sequence':
      return Sequence.fromJson(json);
    case 'ServiceDefinition':
      return ServiceDefinition.fromJson(json);
    case 'Slot':
      return Slot.fromJson(json);
    case 'Specimen':
      return Specimen.fromJson(json);
    case 'StructureDefinition':
      return StructureDefinition.fromJson(json);
    case 'StructureMap':
      return StructureMap.fromJson(json);
    case 'Subscription':
      return Subscription.fromJson(json);
    case 'Substance':
      return Substance.fromJson(json);
    case 'SupplyDelivery':
      return SupplyDelivery.fromJson(json);
    case 'SupplyRequest':
      return SupplyRequest.fromJson(json);
    case 'Task':
      return Task.fromJson(json);
    case 'TestReport':
      return TestReport.fromJson(json);
    case 'TestScript':
      return TestScript.fromJson(json);
    case 'ValueSet':
      return ValueSet.fromJson(json);
    case 'VisionPrescription':
      return VisionPrescription.fromJson(json);
  }
}
