  factory Appointment({
    @Default(R4ResourceType.Appointment)
    @JsonKey(unknownEnumValue: R4ResourceType.Appointment)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Identifier>? identifier,
    @HiveField(12) Code? status,
    @JsonKey(name: '_status') @HiveField(13) Element? statusElement,
    @HiveField(14) CodeableConcept? cancelationReason,
    @HiveField(15) List<CodeableConcept>? serviceCategory,
    @HiveField(16) List<CodeableConcept>? serviceType,
    @HiveField(17) List<CodeableConcept>? specialty,
    @HiveField(18) CodeableConcept? appointmentType,
    @HiveField(19) List<CodeableConcept>? reasonCode,
    @HiveField(20) List<Reference>? reasonReference,
    @HiveField(21) UnsignedInt? priority,
    @JsonKey(name: '_priority') @HiveField(22) Element? priorityElement,
    @HiveField(23) String? description,
    @JsonKey(name: '_description') @HiveField(24) Element? descriptionElement,
    @HiveField(25) List<Reference>? supportingInformation,
    @HiveField(26) Instant? start,
    @JsonKey(name: '_start') @HiveField(27) Element? startElement,
    @HiveField(28) Instant? end,
    @JsonKey(name: '_end') @HiveField(29) Element? endElement,
    @HiveField(30) @HiveField(31) PositiveInt? minutesDuration,
    @JsonKey(name: '_minutesDuration')
    @HiveField(32)
        Element? minutesDurationElement,
    @HiveField(33) List<Reference>? slot,
    @HiveField(34) @HiveField(35) FhirDateTime? created,
    @JsonKey(name: '_created') @HiveField(36) Element? createdElement,
    @HiveField(37) String? comment,
    @JsonKey(name: '_comment') @HiveField(38) Element? commentElement,
    @HiveField(39) String? patientInstruction,
    @JsonKey(name: '_patientInstruction')
    @HiveField(40)
        Element? patientInstructionElement,
    @HiveField(41) List<Reference>? basedOn,
    @HiveField(42) required List<AppointmentParticipant> participant,
    @HiveField(43) List<Period>? requestedPeriod,
  }) = _Appointment;
  factory AppointmentParticipant({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    List<CodeableConcept>? type,
    Reference? actor,
    @JsonKey(name: 'required') Code? required_,
    @JsonKey(name: '_required') Element? requiredElement,
    Code? status,
    @JsonKey(name: '_status') Element? statusElement,
    Period? period,
  }) = _AppointmentParticipant;
  factory AppointmentResponse({
    @Default(R4ResourceType.AppointmentResponse)
    @JsonKey(unknownEnumValue: R4ResourceType.AppointmentResponse)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Identifier>? identifier,
    @HiveField(12) required Reference appointment,
    @HiveField(13) Instant? start,
    @JsonKey(name: '_start') @HiveField(14) Element? startElement,
    @HiveField(15) Instant? end,
    @JsonKey(name: '_end') @HiveField(16) Element? endElement,
    @HiveField(17) List<CodeableConcept>? participantType,
    @HiveField(18) Reference? actor,
    @HiveField(19) Code? participantStatus,
    @JsonKey(name: '_participantStatus')
    @HiveField(20)
        Element? participantStatusElement,
    @HiveField(21) String? comment,
    @JsonKey(name: '_comment') @HiveField(22) Element? commentElement,
  }) = _AppointmentResponse;
  factory Schedule({
    @Default(R4ResourceType.Schedule)
    @JsonKey(unknownEnumValue: R4ResourceType.Schedule)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Identifier>? identifier,
    @HiveField(12) Boolean? active,
    @JsonKey(name: '_active') @HiveField(13) Element? activeElement,
    @HiveField(14) List<CodeableConcept>? serviceCategory,
    @HiveField(15) List<CodeableConcept>? serviceType,
    @HiveField(16) List<CodeableConcept>? specialty,
    @HiveField(17) required List<Reference> actor,
    @HiveField(18) Period? planningHorizon,
    @HiveField(19) String? comment,
    @JsonKey(name: '_comment') @HiveField(20) Element? commentElement,
  }) = _Schedule;
  factory Slot({
    @Default(R4ResourceType.Slot)
    @JsonKey(unknownEnumValue: R4ResourceType.Slot)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Identifier>? identifier,
    @HiveField(12) List<CodeableConcept>? serviceCategory,
    @HiveField(13) @HiveField(14) List<CodeableConcept>? serviceType,
    @HiveField(15) List<CodeableConcept>? specialty,
    @HiveField(16) CodeableConcept? appointmentType,
    @HiveField(17) required Reference schedule,
    @HiveField(18) Code? status,
    @JsonKey(name: '_status') @HiveField(19) Element? statusElement,
    @HiveField(20) Instant? start,
    @JsonKey(name: '_start') @HiveField(21) Element? startElement,
    @HiveField(22) Instant? end,
    @JsonKey(name: '_end') @HiveField(23) Element? endElement,
    @HiveField(24) Boolean? overbooked,
    @JsonKey(name: '_overbooked') @HiveField(25) Element? overbookedElement,
    @HiveField(26) String? comment,
    @JsonKey(name: '_comment') @HiveField(27) Element? commentElement,
  }) = _Slot;
  factory Task({
    @Default(R4ResourceType.Task)
    @JsonKey(unknownEnumValue: R4ResourceType.Task)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Identifier>? identifier,
    @HiveField(12) @HiveField(13) Canonical? instantiatesCanonical,
    @HiveField(14) FhirUri? instantiatesUri,
    @JsonKey(name: '_instantiatesUri')
    @HiveField(15)
        Element? instantiatesUriElement,
    @HiveField(16) List<Reference>? basedOn,
    @HiveField(17) Identifier? groupIdentifier,
    @HiveField(18) List<Reference>? partOf,
    @HiveField(19) Code? status,
    @JsonKey(name: '_status') @HiveField(20) Element? statusElement,
    @HiveField(21) CodeableConcept? statusReason,
    @HiveField(22) CodeableConcept? businessStatus,
    @HiveField(23) @HiveField(24) @HiveField(25) Code? intent,
    @JsonKey(name: '_intent') @HiveField(26) Element? intentElement,
    @HiveField(27) Code? priority,
    @JsonKey(name: '_priority') @HiveField(28) Element? priorityElement,
    @HiveField(29) CodeableConcept? code,
    @HiveField(30) String? description,
    @JsonKey(name: '_description') @HiveField(31) Element? descriptionElement,
    @HiveField(32) Reference? focus,
    @JsonKey(name: 'for') @HiveField(33) Reference? for_,
    @HiveField(34) Reference? encounter,
    @HiveField(35) Period? executionPeriod,
    @HiveField(36) FhirDateTime? authoredOn,
    @JsonKey(name: '_authoredOn') @HiveField(37) Element? authoredOnElement,
    @HiveField(38) FhirDateTime? lastModified,
    @JsonKey(name: '_lastModified') @HiveField(39) Element? lastModifiedElement,
    @HiveField(40) Reference? requester,
    @HiveField(41) List<CodeableConcept>? performerType,
    @HiveField(42) Reference? owner,
    @HiveField(43) Reference? location,
    @HiveField(44) CodeableConcept? reasonCode,
    @HiveField(45) Reference? reasonReference,
    @HiveField(46) List<Reference>? insurance,
    @HiveField(47) List<Annotation>? note,
    @HiveField(48) List<Reference>? relevantHistory,
    @HiveField(49) TaskRestriction? restriction,
    @HiveField(50) List<TaskInput>? input,
    @HiveField(51) List<TaskOutput>? output,
  }) = _Task;
  factory TaskRestriction({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    PositiveInt? repetitions,
    @JsonKey(name: '_repetitions') Element? repetitionsElement,
    Period? period,
    List<Reference>? recipient,
  }) = _TaskRestriction;
  factory TaskInput({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    required CodeableConcept type,
    Base64Binary? valueBase64Binary,
    @JsonKey(name: '_valueBase64Binary') Element? valueBase64BinaryElement,
    Boolean? valueBoolean,
    @JsonKey(name: '_valueBoolean') Element? valueBooleanElement,
    Canonical? valueCanonical,
    @JsonKey(name: '_valueCanonical') Element? valueCanonicalElement,
    Code? valueCode,
    @JsonKey(name: '_valueCode') Element? valueCodeElement,
    Date? valueDate,
    @JsonKey(name: '_valueDate') Element? valueDateElement,
    FhirDateTime? valueDateTime,
    @JsonKey(name: '_valueDateTime') Element? valueDateTimeElement,
    Decimal? valueDecimal,
    @JsonKey(name: '_valueDecimal') Element? valueDecimalElement,
    FhirId? valueId,
    @JsonKey(name: '_valueId') Element? valueIdElement,
    Instant? valueInstant,
    @JsonKey(name: '_valueInstant') Element? valueInstantElement,
    Integer? valueInteger,
    @JsonKey(name: '_valueInteger') Element? valueIntegerElement,
    Markdown? valueMarkdown,
    @JsonKey(name: '_valueMarkdown') Element? valueMarkdownElement,
    Oid? valueOid,
    @JsonKey(name: '_valueOid') Element? valueOidElement,
    PositiveInt? valuePositiveInt,
    @JsonKey(name: '_valuePositiveInt') Element? valuePositiveIntElement,
    String? valueString,
    @JsonKey(name: '_valueString') Element? valueStringElement,
    Time? valueTime,
    @JsonKey(name: '_valueTime') Element? valueTimeElement,
    UnsignedInt? valueUnsignedInt,
    @JsonKey(name: '_valueUnsignedInt') Element? valueUnsignedIntElement,
    FhirUri? valueUri,
    @JsonKey(name: '_valueUri') Element? valueUriElement,
    FhirUrl? valueUrl,
    @JsonKey(name: '_valueUrl') Element? valueUrlElement,
    Uuid? valueUuid,
    @JsonKey(name: '_valueUuid') Element? valueUuidElement,
    Address? valueAddress,
    Age? valueAge,
    Annotation? valueAnnotation,
    Attachment? valueAttachment,
    CodeableConcept? valueCodeableConcept,
    Coding? valueCoding,
    ContactPoint? valueContactPoint,
    Count? valueCount,
    Distance? valueDistance,
    FhirDuration? valueDuration,
    HumanName? valueHumanName,
    Identifier? valueIdentifier,
    Money? valueMoney,
    Period? valuePeriod,
    Quantity? valueQuantity,
    Range? valueRange,
    Ratio? valueRatio,
    Reference? valueReference,
    SampledData? valueSampledData,
    Signature? valueSignature,
    Timing? valueTiming,
    ContactDetail? valueContactDetail,
    Contributor? valueContributor,
    DataRequirement? valueDataRequirement,
    Expression? valueExpression,
    ParameterDefinition? valueParameterDefinition,
    RelatedArtifact? valueRelatedArtifact,
    TriggerDefinition? valueTriggerDefinition,
    UsageContext? valueUsageContext,
    Dosage? valueDosage,
    Meta? valueMeta,
  }) = _TaskInput;
  factory TaskOutput({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    required CodeableConcept type,
    Base64Binary? valueBase64Binary,
    @JsonKey(name: '_valueBase64Binary') Element? valueBase64BinaryElement,
    Boolean? valueBoolean,
    @JsonKey(name: '_valueBoolean') Element? valueBooleanElement,
    Canonical? valueCanonical,
    @JsonKey(name: '_valueCanonical') Element? valueCanonicalElement,
    Code? valueCode,
    @JsonKey(name: '_valueCode') Element? valueCodeElement,
    Date? valueDate,
    @JsonKey(name: '_valueDate') Element? valueDateElement,
    FhirDateTime? valueDateTime,
    @JsonKey(name: '_valueDateTime') Element? valueDateTimeElement,
    Decimal? valueDecimal,
    @JsonKey(name: '_valueDecimal') Element? valueDecimalElement,
    FhirId? valueId,
    @JsonKey(name: '_valueId') Element? valueIdElement,
    Instant? valueInstant,
    @JsonKey(name: '_valueInstant') Element? valueInstantElement,
    Integer? valueInteger,
    @JsonKey(name: '_valueInteger') Element? valueIntegerElement,
    Markdown? valueMarkdown,
    @JsonKey(name: '_valueMarkdown') Element? valueMarkdownElement,
    Oid? valueOid,
    @JsonKey(name: '_valueOid') Element? valueOidElement,
    PositiveInt? valuePositiveInt,
    @JsonKey(name: '_valuePositiveInt') Element? valuePositiveIntElement,
    String? valueString,
    @JsonKey(name: '_valueString') Element? valueStringElement,
    Time? valueTime,
    @JsonKey(name: '_valueTime') Element? valueTimeElement,
    UnsignedInt? valueUnsignedInt,
    @JsonKey(name: '_valueUnsignedInt') Element? valueUnsignedIntElement,
    FhirUri? valueUri,
    @JsonKey(name: '_valueUri') Element? valueUriElement,
    FhirUrl? valueUrl,
    @JsonKey(name: '_valueUrl') Element? valueUrlElement,
    Uuid? valueUuid,
    @JsonKey(name: '_valueUuid') Element? valueUuidElement,
    Address? valueAddress,
    Age? valueAge,
    Annotation? valueAnnotation,
    Attachment? valueAttachment,
    CodeableConcept? valueCodeableConcept,
    Coding? valueCoding,
    ContactPoint? valueContactPoint,
    Count? valueCount,
    Distance? valueDistance,
    FhirDuration? valueDuration,
    HumanName? valueHumanName,
    Identifier? valueIdentifier,
    Money? valueMoney,
    Period? valuePeriod,
    Quantity? valueQuantity,
    Range? valueRange,
    Ratio? valueRatio,
    Reference? valueReference,
    SampledData? valueSampledData,
    Signature? valueSignature,
    Timing? valueTiming,
    ContactDetail? valueContactDetail,
    Contributor? valueContributor,
    DataRequirement? valueDataRequirement,
    Expression? valueExpression,
    ParameterDefinition? valueParameterDefinition,
    RelatedArtifact? valueRelatedArtifact,
    TriggerDefinition? valueTriggerDefinition,
    UsageContext? valueUsageContext,
    Dosage? valueDosage,
    Meta? valueMeta,
  }) = _TaskOutput;
  factory VerificationResult({
    @Default(R4ResourceType.VerificationResult)
    @JsonKey(unknownEnumValue: R4ResourceType.VerificationResult)
    @HiveField(0)
        R4ResourceType resourceType,
    @HiveField(1) String? id,
    @HiveField(2) Meta? meta,
    @HiveField(3) FhirUri? implicitRules,
    @JsonKey(name: '_implicitRules')
    @HiveField(4)
        Element? implicitRulesElement,
    @HiveField(5) Code? language,
    @JsonKey(name: '_language') @HiveField(6) Element? languageElement,
    @HiveField(7) Narrative? text,
    @HiveField(8) List<Resource>? contained,
    @JsonKey(name: 'extension') @HiveField(9) List<FhirExtension>? extension_,
    @HiveField(10) List<FhirExtension>? modifierExtension,
    @HiveField(11) List<Reference>? target,
    @HiveField(12) List<String>? targetLocation,
    @JsonKey(name: '_targetLocation')
    @HiveField(13)
        List<Element?>? targetLocationElement,
    @HiveField(14) CodeableConcept? need,
    @HiveField(15) Code? status,
    @JsonKey(name: '_status') @HiveField(16) Element? statusElement,
    @HiveField(17) FhirDateTime? statusDate,
    @JsonKey(name: '_statusDate') @HiveField(18) Element? statusDateElement,
    @HiveField(19) CodeableConcept? validationType,
    @HiveField(20) List<CodeableConcept>? validationProcess,
    @HiveField(21) Timing? frequency,
    @HiveField(22) FhirDateTime? lastPerformed,
    @JsonKey(name: '_lastPerformed')
    @HiveField(23)
        Element? lastPerformedElement,
    @HiveField(24) Date? nextScheduled,
    @JsonKey(name: '_nextScheduled')
    @HiveField(25)
        Element? nextScheduledElement,
    @HiveField(26) CodeableConcept? failureAction,
    @HiveField(27) List<VerificationResultPrimarySource>? primarySource,
    @HiveField(28) VerificationResultAttestation? attestation,
    @HiveField(29) List<VerificationResultValidator>? validator,
  }) = _VerificationResult;
  factory VerificationResultPrimarySource({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    Reference? who,
    List<CodeableConcept>? type,
    List<CodeableConcept>? communicationMethod,
    CodeableConcept? validationStatus,
    FhirDateTime? validationDate,
    @JsonKey(name: '_validationDate') Element? validationDateElement,
    CodeableConcept? canPushUpdates,
    List<CodeableConcept>? pushTypeAvailable,
  }) = _VerificationResultPrimarySource;
  factory VerificationResultAttestation({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    Reference? who,
    Reference? onBehalfOf,
    CodeableConcept? communicationMethod,
    Date? date,
    @JsonKey(name: '_date') Element? dateElement,
    String? sourceIdentityCertificate,
    @JsonKey(name: '_sourceIdentityCertificate')
        Element? sourceIdentityCertificateElement,
    String? proxyIdentityCertificate,
    @JsonKey(name: '_proxyIdentityCertificate')
        Element? proxyIdentityCertificateElement,
    Signature? proxySignature,
    Signature? sourceSignature,
  }) = _VerificationResultAttestation;
  factory VerificationResultValidator({
    String? id,
    @JsonKey(name: 'extension') List<FhirExtension>? extension_,
    List<FhirExtension>? modifierExtension,
    required Reference organization,
    String? identityCertificate,
    @JsonKey(name: '_identityCertificate') Element? identityCertificateElement,
    Signature? attestationSignature,
  }) = _VerificationResultValidator;
